const TOPICS = [
  { topic: 'Science', words: ['Photosynthesis', 'Gravity', 'Atom', 'Molecule', 'Ecosystem', 'Planet', 'Galaxy', 'Evolution', 'Energy', 'Radiation'] },
  { topic: 'History', words: ['Civilization', 'Invention', 'Dynasty', 'Revolution', 'Empire', 'Artifact', 'Heritage', 'Conquest', 'Monarchy', 'Democracy'] },
  { topic: 'Technology', words: ['Artificial Intelligence', 'Algorithm', 'Cybersecurity', 'Blockchain', 'Quantum', 'Automation', 'Robotics', 'Network', 'Database', 'Encryption'] },
  { topic: 'Philosophy', words: ['Wisdom', 'Ethics', 'Existence', 'Consciousness', 'Virtue', 'Perspective', 'Logic', 'Reasoning', 'Morality', 'Truth'] },
];

const generateQuestions = (level: number) => {
  const topicIndex = Math.floor((level - 21) / 20) % TOPICS.length;
  const topic = TOPICS[topicIndex];
  const word = topic.words[level % topic.words.length];
  
  return [
    { type: 'mcq', question: `"${word}" का अर्थ क्या है?`, options: ['सामान्य', 'कठिन', 'विशेष', 'अज्ञात'], answer: 'विशेष' },
    { type: 'fill', question: `The study of ${word} is fascinating.`, answer: word.toLowerCase(), image: '🔬', hint: `Topic: ${topic.topic}` },
    { type: 'translate', question: `${word} बहुत महत्वपूर्ण है।`, answer: `${word} is very important` },
  ];
};

const baseExercises: any = {
  1: { difficulty: 'easy', questions: [
    { type: 'mcq', question: '"Eat" का अर्थ क्या है?', options: ['दौड़ना', 'खाना', 'सोना', 'लिखना'], answer: 'खाना' },
    { type: 'mcq', question: '"Run" का अर्थ क्या है?', options: ['बैठना', 'दौड़ना', 'सोना', 'पढ़ना'], answer: 'दौड़ना' },
    { type: 'mcq', question: '"Book" का अर्थ क्या है?', options: ['पेन', 'किताब', 'बैग', 'कुर्सी'], answer: 'किताब' },
    { type: 'fill', question: 'I ___ food daily.', answer: 'eat', image: '🍽️', hint: 'खाना खाना' },
    { type: 'fill', question: 'I ___ fast.', answer: 'run', image: '🏃', hint: 'तेज दौड़ना' },
    { type: 'fill', question: 'This is my ___.', answer: 'book', image: '📚', hint: 'किताब' },
    { type: 'translate', question: 'मैं खुश हूँ', answer: 'I am happy' },
    { type: 'translate', question: 'वह मेरा दोस्त है', answer: 'He is my friend' },
    { type: 'translate', question: 'यह मेरा घर है', answer: 'This is my home' },
    { type: 'translate', question: 'पानी ठंडा है', answer: 'Water is cold' },
  ]},
  2: { difficulty: 'easy', questions: [
    { type: 'mcq', question: '"Always" का अर्थ क्या है?', options: ['कभी नहीं', 'हमेशा', 'कभी-कभी', 'जल्दी'], answer: 'हमेशा' },
    { type: 'mcq', question: '"Open" का अर्थ क्या है?', options: ['बंद करना', 'खोलना', 'तोड़ना', 'रखना'], answer: 'खोलना' },
    { type: 'mcq', question: '"Easy" का अर्थ क्या है?', options: ['कठिन', 'आसान', 'बड़ा', 'छोटा'], answer: 'आसान' },
    { type: 'fill', question: 'I ___ help others.', answer: 'always', image: '🤝🙂', hint: 'हमेशा मदद करना' },
    { type: 'fill', question: '___ the door.', answer: 'Open', image: '🚪⬅️', hint: 'दरवाज़ा खोलना' },
    { type: 'fill', question: 'This is ___ question.', answer: 'an easy', image: '🙂👍', hint: 'आसान सवाल' },
    { type: 'translate', question: 'वह एक शिक्षक है', answer: 'He is a teacher' },
    { type: 'translate', question: 'दरवाज़ा खोलो', answer: 'Open the door' },
    { type: 'translate', question: 'यह आसान है', answer: 'This is easy' },
    { type: 'translate', question: 'मैं हमेशा मदद करता हूँ', answer: 'I always help others' },
  ]},
  3: { difficulty: 'medium', questions: [
    { type: 'mcq', question: '"Improve" का अर्थ क्या है?', options: ['गिराना', 'सुधारना', 'तोड़ना', 'बनाना'], answer: 'सुधारना' },
    { type: 'mcq', question: '"Solution" का अर्थ क्या है?', options: ['समस्या', 'समाधान', 'गलती', 'कारण'], answer: 'समाधान' },
    { type: 'mcq', question: '"Goal" का अर्थ क्या है?', options: ['रास्ता', 'लक्ष्य', 'समय', 'काम'], answer: 'लक्ष्य' },
    { type: 'fill', question: 'I want to ___ my English.', answer: 'improve', image: '📈📚', hint: 'बेहतर बनाना' },
    { type: 'fill', question: 'Make a ___ for your future.', answer: 'plan', image: '📅🧠', hint: 'पहले से योजना बनाना' },
    { type: 'fill', question: 'Find the ___.', answer: 'solution', image: '❓➡️✅', hint: 'समस्या का हल' },
    { type: 'translate', question: 'मुझे अपनी अंग्रेज़ी सुधारनी है', answer: 'I want to improve my English' },
    { type: 'translate', question: 'अपना लक्ष्य प्राप्त करो', answer: 'Achieve your goal' },
    { type: 'translate', question: 'समस्या का समाधान ढूंढो', answer: 'Find the solution' },
    { type: 'translate', question: 'रोज अभ्यास करो', answer: 'Practice daily' },
  ]},
  4: { difficulty: 'medium', questions: [
    { type: 'mcq', question: '"Opportunity" का अर्थ क्या है?', options: ['समस्या', 'अवसर', 'समय', 'कारण'], answer: 'अवसर' },
    { type: 'mcq', question: '"Experience" का अर्थ क्या है?', options: ['ज्ञान', 'अनुभव', 'कौशल', 'योजना'], answer: 'अनुभव' },
    { type: 'mcq', question: '"Manage" का अर्थ क्या है?', options: ['बनाना', 'प्रबंधित करना', 'तोड़ना', 'छोड़ना'], answer: 'प्रबंधित करना' },
    { type: 'fill', question: 'Manage your ___.', answer: 'time', image: '⏰', hint: 'समय संभालना' },
    { type: 'fill', question: 'This is a good ___.', answer: 'opportunity', image: '🚪✨', hint: 'अच्छा मौका' },
    { type: 'fill', question: 'Gain ___.', answer: 'experience', image: '🧠📘', hint: 'अनुभव प्राप्त करना' },
    { type: 'translate', question: 'अपने समय का प्रबंधन करो', answer: 'Manage your time' },
    { type: 'translate', question: 'यह एक अच्छा अवसर है', answer: 'This is a good opportunity' },
    { type: 'translate', question: 'अनुभव बहुत महत्वपूर्ण है', answer: 'Experience is very important' },
    { type: 'translate', question: 'अपनी skills सुधारो', answer: 'Improve your skills' },
  ]},
  5: { difficulty: 'hard', questions: [
    { type: 'mcq', question: '"Cold" का अर्थ क्या है?', options: ['गरम', 'ठंडा', 'तेज', 'धीमा'], answer: 'ठंडा' },
    { type: 'mcq', question: '"Day" का अर्थ क्या है?', options: ['रात', 'दिन', 'समय', 'साल'], answer: 'दिन' },
    { type: 'mcq', question: '"Friend" का अर्थ क्या है?', options: ['दुश्मन', 'दोस्त', 'शिक्षक', 'भाई'], answer: 'दोस्त' },
    { type: 'fill', question: 'Water is ___.', answer: 'cold', image: '🧊', hint: 'ठंडा' },
    { type: 'fill', question: 'Today is a good ___.', answer: 'day', image: '🌞', hint: 'दिन' },
    { type: 'fill', question: 'He is my ___.', answer: 'friend', image: '👬', hint: 'दोस्त' },
    { type: 'translate', question: 'पानी ठंडा है', answer: 'Water is cold' },
    { type: 'translate', question: 'आज अच्छा दिन है', answer: 'Today is a good day' },
    { type: 'translate', question: 'वह मेरा दोस्त है', answer: 'He is my friend' },
    { type: 'translate', question: 'मैं घर पर हूँ', answer: 'I am at home' },
  ]},
  6: { difficulty: 'easy', questions: [
    { type: 'mcq', question: '"Problem" का अर्थ क्या है?', options: ['समाधान', 'समस्या', 'लक्ष्य', 'कारण'], answer: 'समस्या' },
    { type: 'mcq', question: '"Reason" का अर्थ क्या है?', options: ['उत्तर', 'कारण', 'समय', 'योजना'], answer: 'कारण' },
    { type: 'mcq', question: '"Result" का अर्थ क्या है?', options: ['शुरुआत', 'परिणाम', 'गलती', 'रास्ता'], answer: 'परिणाम' },
    { type: 'fill', question: 'This is a ___.', answer: 'problem', image: '❗', hint: 'समस्या' },
    { type: 'fill', question: 'Tell the ___.', answer: 'reason', image: '🤔', hint: 'कारण' },
    { type: 'fill', question: 'The ___ is good.', answer: 'result', image: '📊', hint: 'परिणाम' },
    { type: 'translate', question: 'यह एक समस्या है', answer: 'This is a problem' },
    { type: 'translate', question: 'कारण बताओ', answer: 'Tell the reason' },
    { type: 'translate', question: 'परिणाम अच्छा है', answer: 'The result is good' },
    { type: 'translate', question: 'समाधान ढूंढो', answer: 'Find the solution' },
  ]},
  7: { difficulty: 'easy', questions: [
    { type: 'mcq', question: '"Improve" का अर्थ क्या है?', options: ['गिराना', 'सुधारना', 'रोकना', 'छोड़ना'], answer: 'सुधारना' },
    { type: 'mcq', question: '"Develop" का अर्थ क्या है?', options: ['तोड़ना', 'विकसित करना', 'गिराना', 'रोकना'], answer: 'विकसित करना' },
    { type: 'mcq', question: '"Create" का अर्थ क्या है?', options: ['खत्म करना', 'बनाना', 'गिराना', 'रोकना'], answer: 'बनाना' },
    { type: 'fill', question: 'I want to ___ my skills.', answer: 'improve', image: '📈', hint: 'सुधारना' },
    { type: 'fill', question: '___ your future.', answer: 'develop', image: '🏗️', hint: 'विकसित करना' },
    { type: 'fill', question: '___ something new.', answer: 'create', image: '🎨', hint: 'बनाना' },
    { type: 'translate', question: 'अपनी skills सुधारो', answer: 'Improve your skills' },
    { type: 'translate', question: 'अपना भविष्य बनाओ', answer: 'Develop your future' },
    { type: 'translate', question: 'कुछ नया बनाओ', answer: 'Create something new' },
    { type: 'translate', question: 'रोज सीखो', answer: 'Learn daily' },
  ]},
  8: { difficulty: 'medium', questions: [
    { type: 'mcq', question: '"Opportunity" का अर्थ क्या है?', options: ['समस्या', 'अवसर', 'समय', 'कारण'], answer: 'अवसर' },
    { type: 'mcq', question: '"Decision" का अर्थ क्या है?', options: ['सवाल', 'निर्णय', 'उत्तर', 'कारण'], answer: 'निर्णय' },
    { type: 'mcq', question: '"Risk" का अर्थ क्या है?', options: ['आराम', 'जोखिम', 'समय', 'काम'], answer: 'जोखिम' },
    { type: 'fill', question: 'Grab the ___.', answer: 'opportunity', image: '🚪✨', hint: 'अवसर' },
    { type: 'fill', question: 'Make a ___.', answer: 'decision', image: '🤔✔️', hint: 'निर्णय' },
    { type: 'fill', question: 'Take a ___.', answer: 'risk', image: '⚠️', hint: 'जोखिम' },
    { type: 'translate', question: 'अवसर पकड़ो', answer: 'Grab the opportunity' },
    { type: 'translate', question: 'सही निर्णय लो', answer: 'Make the right decision' },
    { type: 'translate', question: 'जोखिम लो', answer: 'Take a risk' },
    { type: 'translate', question: 'चुनौती स्वीकार करो', answer: 'Accept the challenge' },
  ]},
  9: { difficulty: 'medium', questions: [
    { type: 'mcq', question: '"Strategy" का अर्थ क्या है?', options: ['योजना', 'रणनीति', 'कारण', 'समय'], answer: 'रणनीति' },
    { type: 'mcq', question: '"Performance" का अर्थ क्या है?', options: ['खेल', 'प्रदर्शन', 'काम', 'योजना'], answer: 'प्रदर्शन' },
    { type: 'mcq', question: '"Efficient" का अर्थ क्या है?', options: ['धीमा', 'कुशल', 'कमजोर', 'गलत'], answer: 'कुशल' },
    { type: 'fill', question: 'Make a ___.', answer: 'strategy', image: '🧠📊', hint: 'रणनीति' },
    { type: 'fill', question: 'Improve your ___.', answer: 'performance', image: '📈', hint: 'प्रदर्शन' },
    { type: 'fill', question: 'Be ___.', answer: 'efficient', image: '⚡', hint: 'कुशल' },
    { type: 'translate', question: 'एक अच्छी रणनीति बनाओ', answer: 'Make a good strategy' },
    { type: 'translate', question: 'अपना प्रदर्शन सुधारो', answer: 'Improve your performance' },
    { type: 'translate', question: 'कुशल बनो', answer: 'Be efficient' },
    { type: 'translate', question: 'लगातार मेहनत करो', answer: 'Work consistently' },
  ]},
  10: { difficulty: 'hard', questions: [
    { type: 'mcq', question: '"Eat" का अर्थ क्या है?', options: ['दौड़ना', 'खाना', 'सोना', 'लिखना'], answer: 'खाना' },
    { type: 'mcq', question: '"Run" का अर्थ क्या है?', options: ['बैठना', 'दौड़ना', 'सोना', 'पढ़ना'], answer: 'दौड़ना' },
    { type: 'mcq', question: '"Book" का अर्थ क्या है?', options: ['पेन', 'किताब', 'बैग', 'कुर्सी'], answer: 'किताब' },
    { type: 'fill', question: 'I ___ food daily.', answer: 'eat', image: '🍽️', hint: 'खाना' },
    { type: 'fill', question: 'I ___ fast.', answer: 'run', image: '🏃', hint: 'दौड़ना' },
    { type: 'fill', question: 'This is my ___.', answer: 'book', image: '📚', hint: 'किताब' },
    { type: 'translate', question: 'मैं खुश हूँ', answer: 'I am happy' },
    { type: 'translate', question: 'वह मेरा दोस्त है', answer: 'He is my friend' },
    { type: 'translate', question: 'यह मेरा घर है', answer: 'This is my home' },
    { type: 'translate', question: 'पानी ठंडा है', answer: 'Water is cold' },
  ]},
  11: { difficulty: 'easy', questions: [
    { type: 'mcq', question: '"Happy" का अर्थ क्या है?', options: ['दुखी', 'खुश', 'गुस्सा', 'शांत'], answer: 'खुश' },
    { type: 'mcq', question: '"Sad" का अर्थ क्या है?', options: ['खुश', 'दुखी', 'मज़ेदार', 'उत्साहित'], answer: 'दुखी' },
    { type: 'mcq', question: '"Big" का अर्थ क्या है?', options: ['छोटा', 'बड़ा', 'लंबा', 'पतला'], answer: 'बड़ा' },
    { type: 'fill', question: 'I am very ___.', answer: 'happy', image: '😊', hint: 'खुश' },
    { type: 'fill', question: 'Don\'t be ___.', answer: 'sad', image: '😢', hint: 'दुखी' },
    { type: 'fill', question: 'That is a ___ house.', answer: 'big', image: '🏠', hint: 'बड़ा' },
    { type: 'translate', question: 'मैं खुश हूँ', answer: 'I am happy' },
    { type: 'translate', question: 'वह दुखी है', answer: 'He is sad' },
    { type: 'translate', question: 'यह एक बड़ा घर है', answer: 'This is a big house' },
    { type: 'translate', question: 'तुम बहुत अच्छे हो', answer: 'You are very good' },
  ]},
  12: { difficulty: 'easy', questions: [
    { type: 'mcq', question: '"Fast" का अर्थ क्या है?', options: ['धीमा', 'तेज', 'लंबा', 'छोटा'], answer: 'तेज' },
    { type: 'mcq', question: '"Slow" का अर्थ क्या है?', options: ['तेज', 'धीमा', 'बड़ा', 'छोटा'], answer: 'धीमा' },
    { type: 'mcq', question: '"Strong" का अर्थ क्या है?', options: ['कमजोर', 'मजबूत', 'लंबा', 'पतला'], answer: 'मजबूत' },
    { type: 'fill', question: 'He runs ___.', answer: 'fast', image: '⚡', hint: 'तेज' },
    { type: 'fill', question: 'The turtle is ___.', answer: 'slow', image: '🐢', hint: 'धीमा' },
    { type: 'fill', question: 'He is very ___.', answer: 'strong', image: '💪', hint: 'मजबूत' },
    { type: 'translate', question: 'वह तेज दौड़ता है', answer: 'He runs fast' },
    { type: 'translate', question: 'कछुआ धीमा है', answer: 'The turtle is slow' },
    { type: 'translate', question: 'वह बहुत मजबूत है', answer: 'He is very strong' },
    { type: 'translate', question: 'तेज चलो', answer: 'Walk fast' },
  ]},
  13: { difficulty: 'medium', questions: [
    { type: 'mcq', question: '"Learn" का अर्थ क्या है?', options: ['पढ़ना', 'सीखना', 'लिखना', 'सोना'], answer: 'सीखना' },
    { type: 'mcq', question: '"Teach" का अर्थ क्या है?', options: ['सीखना', 'पढ़ाना', 'लिखना', 'सोना'], answer: 'पढ़ाना' },
    { type: 'mcq', question: '"Study" का अर्थ क्या है?', options: ['पढ़ना', 'सीखना', 'लिखना', 'सोना'], answer: 'पढ़ना' },
    { type: 'fill', question: 'I want to ___ English.', answer: 'learn', image: '🧠', hint: 'सीखना' },
    { type: 'fill', question: 'Teachers ___ us.', answer: 'teach', image: '👩‍🏫', hint: 'पढ़ाना' },
    { type: 'fill', question: 'I ___ every day.', answer: 'study', image: '📖', hint: 'पढ़ना' },
    { type: 'translate', question: 'मैं अंग्रेज़ी सीखना चाहता हूँ', answer: 'I want to learn English' },
    { type: 'translate', question: 'शिक्षक हमें पढ़ाते हैं', answer: 'Teachers teach us' },
    { type: 'translate', question: 'मैं रोज़ पढ़ता हूँ', answer: 'I study every day' },
    { type: 'translate', question: 'सीखना महत्वपूर्ण है', answer: 'Learning is important' },
  ]},
  14: { difficulty: 'medium', questions: [
    { type: 'mcq', question: '"Work" का अर्थ क्या है?', options: ['आराम', 'काम', 'खेल', 'सोना'], answer: 'काम' },
    { type: 'mcq', question: '"Play" का अर्थ क्या है?', options: ['पढ़ना', 'खेलना', 'लिखना', 'सोना'], answer: 'खेलना' },
    { type: 'mcq', question: '"Rest" का अर्थ क्या है?', options: ['काम', 'आराम', 'दौड़ना', 'सोना'], answer: 'आराम' },
    { type: 'fill', question: 'I have to ___.', answer: 'work', image: '💼', hint: 'काम' },
    { type: 'fill', question: 'Let\'s ___ football.', answer: 'play', image: '⚽', hint: 'खेलना' },
    { type: 'fill', question: 'Take some ___.', answer: 'rest', image: '😴', hint: 'आराम' },
    { type: 'translate', question: 'मुझे काम करना है', answer: 'I have to work' },
    { type: 'translate', question: 'चलो फुटबॉल खेलते हैं', answer: 'Let\'s play football' },
    { type: 'translate', question: 'थोड़ा आराम करो', answer: 'Take some rest' },
    { type: 'translate', question: 'काम और खेल ज़रूरी है', answer: 'Work and play is important' },
  ]},
  15: { difficulty: 'hard', questions: [
    { type: 'mcq', question: '"Difficult" का अर्थ क्या है?', options: ['आसान', 'कठिन', 'बड़ा', 'छोटा'], answer: 'कठिन' },
    { type: 'mcq', question: '"Simple" का अर्थ क्या है?', options: ['कठिन', 'सरल', 'बड़ा', 'छोटा'], answer: 'सरल' },
    { type: 'mcq', question: '"Complex" का अर्थ क्या है?', options: ['सरल', 'जटिल', 'बड़ा', 'छोटा'], answer: 'जटिल' },
    { type: 'fill', question: 'This is ___.', answer: 'difficult', image: '🧩', hint: 'कठिन' },
    { type: 'fill', question: 'Keep it ___.', answer: 'simple', image: '✨', hint: 'सरल' },
    { type: 'fill', question: 'It is ___.', answer: 'complex', image: '🌀', hint: 'जटिल' },
    { type: 'translate', question: 'यह कठिन है', answer: 'This is difficult' },
    { type: 'translate', question: 'इसे सरल रखो', answer: 'Keep it simple' },
    { type: 'translate', question: 'यह जटिल है', answer: 'It is complex' },
    { type: 'translate', question: 'सरल जीवन जियो', answer: 'Live a simple life' },
  ]},
  16: { difficulty: 'easy', questions: [
    { type: 'mcq', question: '"Morning" का अर्थ क्या है?', options: ['रात', 'सुबह', 'शाम', 'दोपहर'], answer: 'सुबह' },
    { type: 'mcq', question: '"Evening" का अर्थ क्या है?', options: ['सुबह', 'शाम', 'रात', 'दोपहर'], answer: 'शाम' },
    { type: 'mcq', question: '"Night" का अर्थ क्या है?', options: ['सुबह', 'शाम', 'रात', 'दोपहर'], answer: 'रात' },
    { type: 'fill', question: 'Good ___.', answer: 'morning', image: '🌅', hint: 'सुबह' },
    { type: 'fill', question: 'Good ___.', answer: 'evening', image: '🌇', hint: 'शाम' },
    { type: 'fill', question: 'Good ___.', answer: 'night', image: '🌙', hint: 'रात' },
    { type: 'translate', question: 'सुप्रभात', answer: 'Good morning' },
    { type: 'translate', question: 'शुभ संध्या', answer: 'Good evening' },
    { type: 'translate', question: 'शुभ रात्रि', answer: 'Good night' },
    { type: 'translate', question: 'मैं सुबह उठता हूँ', answer: 'I wake up in the morning' },
  ]},
  17: { difficulty: 'easy', questions: [
    { type: 'mcq', question: '"Water" का अर्थ क्या है?', options: ['दूध', 'पानी', 'जूस', 'चाय'], answer: 'पानी' },
    { type: 'mcq', question: '"Food" का अर्थ क्या है?', options: ['पानी', 'खाना', 'फल', 'सब्जी'], answer: 'खाना' },
    { type: 'mcq', question: '"Fruit" का अर्थ क्या है?', options: ['पानी', 'खाना', 'फल', 'सब्जी'], answer: 'फल' },
    { type: 'fill', question: 'Drink ___.', answer: 'water', image: '💧', hint: 'पानी' },
    { type: 'fill', question: 'Eat healthy ___.', answer: 'food', image: '🍎', hint: 'खाना' },
    { type: 'fill', question: 'Eat a ___.', answer: 'fruit', image: '🍌', hint: 'फल' },
    { type: 'translate', question: 'पानी पियो', answer: 'Drink water' },
    { type: 'translate', question: 'स्वस्थ खाना खाओ', answer: 'Eat healthy food' },
    { type: 'translate', question: 'फल खाओ', answer: 'Eat a fruit' },
    { type: 'translate', question: 'मुझे भूख लगी है', answer: 'I am hungry' },
  ]},
  18: { difficulty: 'medium', questions: [
    { type: 'mcq', question: '"Listen" का अर्थ क्या है?', options: ['बोलना', 'सुनना', 'लिखना', 'पढ़ना'], answer: 'सुनना' },
    { type: 'mcq', question: '"Speak" का अर्थ क्या है?', options: ['सुनना', 'बोलना', 'लिखना', 'पढ़ना'], answer: 'बोलना' },
    { type: 'mcq', question: '"Write" का अर्थ क्या है?', options: ['सुनना', 'बोलना', 'लिखना', 'पढ़ना'], answer: 'लिखना' },
    { type: 'fill', question: '___ to me.', answer: 'listen', image: '👂', hint: 'सुनना' },
    { type: 'fill', question: '___ English.', answer: 'speak', image: '🗣️', hint: 'बोलना' },
    { type: 'fill', question: '___ your name.', answer: 'write', image: '✍️', hint: 'लिखना' },
    { type: 'translate', question: 'मेरी बात सुनो', answer: 'Listen to me' },
    { type: 'translate', question: 'अंग्रेज़ी बोलो', answer: 'Speak English' },
    { type: 'translate', question: 'अपना नाम लिखो', answer: 'Write your name' },
    { type: 'translate', question: 'ध्यान से सुनो', answer: 'Listen carefully' },
  ]},
  19: { difficulty: 'medium', questions: [
    { type: 'mcq', question: '"Time" का अर्थ क्या है?', options: ['पैसा', 'समय', 'काम', 'जगह'], answer: 'समय' },
    { type: 'mcq', question: '"Money" का अर्थ क्या है?', options: ['समय', 'पैसा', 'काम', 'जगह'], answer: 'पैसा' },
    { type: 'mcq', question: '"Place" का अर्थ क्या है?', options: ['समय', 'पैसा', 'काम', 'जगह'], answer: 'जगह' },
    { type: 'fill', question: '___ is precious.', answer: 'time', image: '⏳', hint: 'समय' },
    { type: 'fill', question: 'Save ___.', answer: 'money', image: '💰', hint: 'पैसा' },
    { type: 'fill', question: 'This is a nice ___.', answer: 'place', image: '📍', hint: 'जगह' },
    { type: 'translate', question: 'समय कीमती है', answer: 'Time is precious' },
    { type: 'translate', question: 'पैसे बचाओ', answer: 'Save money' },
    { type: 'translate', question: 'यह एक अच्छी जगह है', answer: 'This is a nice place' },
    { type: 'translate', question: 'समय पर आओ', answer: 'Come on time' },
  ]},
  20: { difficulty: 'hard', questions: [
    { type: 'mcq', question: '"Believe" का अर्थ क्या है?', options: ['संदेह', 'विश्वास', 'डर', 'प्यार'], answer: 'विश्वास' },
    { type: 'mcq', question: '"Achieve" का अर्थ क्या है?', options: ['हारना', 'प्राप्त करना', 'डरना', 'सोना'], answer: 'प्राप्त करना' },
    { type: 'mcq', question: '"Success" का अर्थ क्या है?', options: ['हार', 'सफलता', 'डर', 'सोना'], answer: 'सफलता' },
    { type: 'fill', question: '___ in yourself.', answer: 'believe', image: '✨', hint: 'विश्वास' },
    { type: 'fill', question: '___ your goals.', answer: 'achieve', image: '🎯', hint: 'प्राप्त करना' },
    { type: 'fill', question: 'Work for ___.', answer: 'success', image: '🏆', hint: 'सफलता' },
    { type: 'translate', question: 'खुद पर विश्वास करो', answer: 'Believe in yourself' },
    { type: 'translate', question: 'अपने लक्ष्य प्राप्त करो', answer: 'Achieve your goals' },
    { type: 'translate', question: 'सफलता के लिए काम करो', answer: 'Work for success' },
    { type: 'translate', question: 'कभी हार मत मानो', answer: 'Never give up' },
  ]},
};

const dynamicExercises: any = {};
for (let i = 21; i <= 100; i++) {
  dynamicExercises[i] = {
    difficulty: i % 5 === 0 ? 'hard' : (i % 3 === 0 ? 'medium' : 'easy'),
    questions: generateQuestions(i)
  };
}

export const EXERCISES = { ...baseExercises, ...dynamicExercises };
