export const WORD_LIST = [
  // Level 1 (Words 1-100)
  { hindi: "खाना", english: "Eat", example: "I eat food daily.", exampleHindi: "मैं रोज खाना खाता हूँ" },
  { hindi: "जाना", english: "Go", example: "I go to school.", exampleHindi: "मैं स्कूल जाता हूँ" },
  { hindi: "आना", english: "Come", example: "Please come here.", exampleHindi: "कृपया यहाँ आओ" },
  { hindi: "बनाना", english: "Make", example: "I make a cake.", exampleHindi: "मैं केक बनाता हूँ" },
  { hindi: "लेना", english: "Take", example: "Take this book.", exampleHindi: "यह किताब लो" },
  { hindi: "देना", english: "Give", example: "Give me water.", exampleHindi: "मुझे पानी दो" },
  { hindi: "दौड़ना", english: "Run", example: "He runs fast.", exampleHindi: "वह तेज दौड़ता है" },
  { hindi: "पढ़ना", english: "Read", example: "I read a book.", exampleHindi: "मैं किताब पढ़ता हूँ" },
  { hindi: "लिखना", english: "Write", example: "Write your name.", exampleHindi: "अपना नाम लिखो" },
  { hindi: "बोलना", english: "Speak", example: "Speak clearly.", exampleHindi: "साफ बोलो" },
  { hindi: "पानी", english: "Water", example: "Drink water.", exampleHindi: "पानी पियो" },
  { hindi: "खाना", english: "Food", example: "Food is ready.", exampleHindi: "खाना तैयार है" },
  { hindi: "किताब", english: "Book", example: "This is my book.", exampleHindi: "यह मेरी किताब है" },
  { hindi: "कलम", english: "Pen", example: "I have a pen.", exampleHindi: "मेरे पास कलम है" },
  { hindi: "स्कूल", english: "School", example: "My school is big.", exampleHindi: "मेरा स्कूल बड़ा है" },
  { hindi: "खुश", english: "Happy", example: "I am happy.", exampleHindi: "मैं खुश हूँ" },
  { hindi: "दुखी", english: "Sad", example: "She is sad.", exampleHindi: "वह दुखी है" },
  { hindi: "बड़ा", english: "Big", example: "This is a big house.", exampleHindi: "यह बड़ा घर है" },
  { hindi: "छोटा", english: "Small", example: "This is a small cat.", exampleHindi: "यह छोटी बिल्ली है" },
  { hindi: "अच्छा", english: "Good", example: "This is good.", exampleHindi: "यह अच्छा है" },
  { hindi: "बुरा", english: "Bad", example: "This is bad.", exampleHindi: "यह बुरा है" },
  { hindi: "तेज", english: "Fast", example: "He is fast.", exampleHindi: "वह तेज है" },
  { hindi: "धीमा", english: "Slow", example: "The turtle is slow.", exampleHindi: "कछुआ धीमा है" },
  { hindi: "गरम", english: "Hot", example: "Tea is hot.", exampleHindi: "चाय गरम है" },
  { hindi: "ठंडा", english: "Cold", example: "Water is cold.", exampleHindi: "पानी ठंडा है" },
  { hindi: "दिन", english: "Day", example: "Today is a good day.", exampleHindi: "आज अच्छा दिन है" },
  { hindi: "रात", english: "Night", example: "It is night now.", exampleHindi: "अब रात है" },
  { hindi: "दोस्त", english: "Friend", example: "He is my friend.", exampleHindi: "वह मेरा दोस्त है" },
  { hindi: "परिवार", english: "Family", example: "I love my family.", exampleHindi: "मैं अपने परिवार से प्यार करता हूँ" },
  { hindi: "घर", english: "Home", example: "I am at home.", exampleHindi: "मैं घर पर हूँ" },
  { hindi: "पहले", english: "Before", example: "Wash hands before eating.", exampleHindi: "खाने से पहले हाथ धोओ" },
  { hindi: "बाद में", english: "After", example: "Come after lunch.", exampleHindi: "खाने के बाद आओ" },
  { hindi: "हमेशा", english: "Always", example: "I always help others.", exampleHindi: "मैं हमेशा मदद करता हूँ" },
  { hindi: "कभी नहीं", english: "Never", example: "I never lie.", exampleHindi: "मैं कभी झूठ नहीं बोलता" },
  { hindi: "कभी-कभी", english: "Sometimes", example: "I sometimes play.", exampleHindi: "मैं कभी-कभी खेलता हूँ" },
  { hindi: "शिक्षक", english: "Teacher", example: "My teacher is kind.", exampleHindi: "मेरे शिक्षक दयालु हैं" },
  { hindi: "विद्यार्थी", english: "Student", example: "I am a student.", exampleHindi: "मैं विद्यार्थी हूँ" },
  { hindi: "कक्षा", english: "Class", example: "My class is clean.", exampleHindi: "मेरी कक्षा साफ है" },
  { hindi: "खोलना", english: "Open", example: "Open the door.", exampleHindi: "दरवाजा खोलो" },
  { hindi: "बंद करना", english: "Close", example: "Close the window.", exampleHindi: "खिड़की बंद करो" },
  { hindi: "शुरू करना", english: "Start", example: "Start your work.", exampleHindi: "काम शुरू करो" },
  { hindi: "खत्म करना", english: "Finish", example: "Finish homework.", exampleHindi: "होमवर्क खत्म करो" },
  { hindi: "सीखना", english: "Learn", example: "I learn English.", exampleHindi: "मैं अंग्रेजी सीखता हूँ" },
  { hindi: "सिखाना", english: "Teach", example: "She teaches math.", exampleHindi: "वह गणित सिखाती है" },
  { hindi: "पूछना", english: "Ask", example: "Ask a question.", exampleHindi: "सवाल पूछो" },
  { hindi: "उत्तर देना", english: "Answer", example: "Answer correctly.", exampleHindi: "सही उत्तर दो" },
  { hindi: "समझना", english: "Understand", example: "I understand this.", exampleHindi: "मैं इसे समझता हूँ" },
  { hindi: "भूलना", english: "Forget", example: "Don’t forget.", exampleHindi: "मत भूलो" },
  { hindi: "साफ करना", english: "Clean", example: "Clean your room.", exampleHindi: "कमरा साफ करो" },
  { hindi: "गंदा", english: "Dirty", example: "The floor is dirty.", exampleHindi: "फर्श गंदा है" },
  { hindi: "सुंदर", english: "Beautiful", example: "The flower is beautiful.", exampleHindi: "फूल सुंदर है" },
  { hindi: "बदसूरत", english: "Ugly", example: "This is ugly.", exampleHindi: "यह बदसूरत है" },
  { hindi: "आसान", english: "Easy", example: "This is easy.", exampleHindi: "यह आसान है" },
  { hindi: "कठिन", english: "Difficult", example: "This is difficult.", exampleHindi: "यह कठिन है" },
  { hindi: "पास", english: "Near", example: "The shop is near.", exampleHindi: "दुकान पास है" },
  { hindi: "दूर", english: "Far", example: "The school is far.", exampleHindi: "स्कूल दूर है" },
  { hindi: "सही", english: "Right", example: "Your answer is right.", exampleHindi: "जवाब सही है" },
  { hindi: "गलत", english: "Wrong", example: "This is wrong.", exampleHindi: "यह गलत है" },
  { hindi: "जल्दी", english: "Early", example: "Wake up early.", exampleHindi: "जल्दी उठो" },
  { hindi: "देर", english: "Late", example: "Don’t be late.", exampleHindi: "देर मत करो" },
  { hindi: "आज", english: "Today", example: "Today is Sunday.", exampleHindi: "आज रविवार है" },
  { hindi: "कल", english: "Tomorrow", example: "Tomorrow is holiday.", exampleHindi: "कल छुट्टी है" },
  { hindi: "कल", english: "Yesterday", example: "Yesterday was fun.", exampleHindi: "कल मजेदार था" },
  { hindi: "खरीदना", english: "Buy", example: "I buy fruits.", exampleHindi: "मैं फल खरीदता हूँ" },
  { hindi: "बेचना", english: "Sell", example: "He sells vegetables.", exampleHindi: "वह सब्जी बेचता है" },
  { hindi: "लाना", english: "Bring", example: "Bring water.", exampleHindi: "पानी लाओ" },
  { hindi: "भेजना", english: "Send", example: "Send message.", exampleHindi: "संदेश भेजो" },
  { hindi: "फोन करना", english: "Call", example: "Call me later.", exampleHindi: "बाद में कॉल करो" },
  { hindi: "खेलना", english: "Play", example: "I play football.", exampleHindi: "मैं फुटबॉल खेलता हूँ" },
  { hindi: "काम करना", english: "Work", example: "I work hard.", exampleHindi: "मैं मेहनत करता हूँ" },
  { hindi: "आराम करना", english: "Rest", example: "Take rest.", exampleHindi: "आराम करो" },
  { hindi: "सोना", english: "Sleep", example: "I sleep early.", exampleHindi: "मैं जल्दी सोता हूँ" },
  { hindi: "जागना", english: "Wake", example: "Wake up now.", exampleHindi: "अब जागो" },
  { hindi: "प्यार करना", english: "Love", example: "I love my parents.", exampleHindi: "मैं माता-पिता से प्यार करता हूँ" },
  { hindi: "पसंद करना", english: "Like", example: "I like mango.", exampleHindi: "मुझे आम पसंद है" },
  { hindi: "नफरत करना", english: "Hate", example: "I hate lies.", exampleHindi: "मुझे झूठ से नफरत है" },
  { hindi: "मदद करना", english: "Help", example: "Help me.", exampleHindi: "मेरी मदद करो" },
  { hindi: "कोशिश करना", english: "Try", example: "Try again.", exampleHindi: "फिर कोशिश करो" },
  { hindi: "सुधारना", english: "Improve", example: "I want to improve my English.", exampleHindi: "मैं अंग्रेजी सुधारना चाहता हूँ" },
  { hindi: "निर्णय लेना", english: "Decide", example: "I decide my future.", exampleHindi: "मैं अपना भविष्य तय करता हूँ" },
  { hindi: "समझाना", english: "Explain", example: "Please explain this.", exampleHindi: "इसे समझाओ" },
  { hindi: "चर्चा करना", english: "Discuss", example: "We discuss problems.", exampleHindi: "हम चर्चा करते हैं" },
  { hindi: "चुनना", english: "Choose", example: "Choose the answer.", exampleHindi: "उत्तर चुनो" },
  { hindi: "समस्या", english: "Problem", example: "This is a problem.", exampleHindi: "यह समस्या है" },
  { hindi: "समाधान", english: "Solution", example: "Find solution.", exampleHindi: "समाधान ढूंढो" },
  { hindi: "कारण", english: "Reason", example: "Tell the reason.", exampleHindi: "कारण बताओ" },
  { hindi: "परिणाम", english: "Result", example: "Result is good.", exampleHindi: "परिणाम अच्छा है" },
  { hindi: "लक्ष्य", english: "Goal", example: "My goal is success.", exampleHindi: "मेरा लक्ष्य सफलता है" },
  { hindi: "योजना बनाना", english: "Plan", example: "Make a plan.", exampleHindi: "योजना बनाओ" },
  { hindi: "तैयार करना", english: "Prepare", example: "Prepare for exam.", exampleHindi: "परीक्षा की तैयारी करो" },
  { hindi: "अभ्यास करना", english: "Practice", example: "Practice daily.", exampleHindi: "रोज अभ्यास करो" },
  { hindi: "दोहराना", english: "Repeat", example: "Repeat again.", exampleHindi: "फिर दोहराओ" },
  { hindi: "याद रखना", english: "Remember", example: "Remember this.", exampleHindi: "इसे याद रखो" },
  { hindi: "भूलना", english: "Forget", example: "Don’t forget.", exampleHindi: "मत भूलो" },
  { hindi: "विश्वास करना", english: "Believe", example: "Believe yourself.", exampleHindi: "खुद पर विश्वास करो" },
  { hindi: "प्राप्त करना", english: "Achieve", example: "Achieve success.", exampleHindi: "सफलता पाओ" },
  { hindi: "असफल होना", english: "Fail", example: "Don’t fail.", exampleHindi: "असफल मत हो" },
  { hindi: "सफलता", english: "Success", example: "Success comes.", exampleHindi: "सफलता आती है" },
  { hindi: "मेहनती", english: "Hard", example: "Work hard.", exampleHindi: "मेहनत करो" },

  // Level 2 (Words 101-200) - User Provided List
  { hindi: "छोड़ देना", english: "Abandon", example: "Never abandon your dreams.", exampleHindi: "अपने सपनों को कभी मत छोड़ो" },
  { hindi: "क्षमता", english: "Ability", example: "He has the ability to sing.", exampleHindi: "उसमें गाने की क्षमता है" },
  { hindi: "स्वीकार करना", english: "Accept", example: "Accept the challenge.", exampleHindi: "चुनौती को स्वीकार करें" },
  { hindi: "प्राप्त करना", english: "Achieve", example: "Work hard to achieve goals.", exampleHindi: "लक्ष्यों को प्राप्त करने के लिए कड़ी मेहनत करें" },
  { hindi: "सक्रिय", english: "Active", example: "Stay active every day.", exampleHindi: "हर रोज सक्रिय रहें" },
  { hindi: "सलाह", english: "Advice", example: "Take my advice.", exampleHindi: "मेरी सलाह लें" },
  { hindi: "अनुमति देना", english: "Allow", example: "Please allow me to go.", exampleHindi: "कृपया मुझे जाने की अनुमति दें" },
  { hindi: "अद्भुत", english: "Amazing", example: "The view is amazing.", exampleHindi: "नजारा अद्भुत है" },
  { hindi: "प्राचीन", english: "Ancient", example: "This is an ancient temple.", exampleHindi: "यह एक प्राचीन मंदिर है" },
  { hindi: "गुस्सा", english: "Angry", example: "Don't be angry.", exampleHindi: "गुस्सा मत करो" },
  { hindi: "दिखाई देना", english: "Appear", example: "The stars appear at night.", exampleHindi: "रात में तारे दिखाई देते हैं" },
  { hindi: "आवेदन करना", english: "Apply", example: "Apply for the job.", exampleHindi: "नौकरी के लिए आवेदन करें" },
  { hindi: "बहस करना", english: "Argue", example: "Don't argue with elders.", exampleHindi: "बड़ों के साथ बहस न करें" },
  { hindi: "पहुँचना", english: "Arrive", example: "The train will arrive soon.", exampleHindi: "ट्रेन जल्द ही पहुंचेगी" },
  { hindi: "हमला करना", english: "Attack", example: "Don't attack anyone.", exampleHindi: "किसी पर हमला मत करो" },
  { hindi: "बचना", english: "Avoid", example: "Avoid bad habits.", exampleHindi: "बुरी आदतों से बचें" },
  { hindi: "संतुलन", english: "Balance", example: "Maintain a balance.", exampleHindi: "संतुलन बनाए रखें" },
  { hindi: "विश्वास करना", english: "Believe", example: "Believe in yourself.", exampleHindi: "खुद पर विश्वास करें" },
  { hindi: "बहादुर", english: "Brave", example: "He is a brave boy.", exampleHindi: "वह एक बहादुर लड़का है" },
  { hindi: "चमकदार", english: "Bright", example: "The sun is bright.", exampleHindi: "सूरज चमकदार है" },
  { hindi: "शांत", english: "Calm", example: "Stay calm.", exampleHindi: "शांत रहो" },
  { hindi: "देखभाल", english: "Care", example: "Take care of yourself.", exampleHindi: "अपना ख्याल रखें" },
  { hindi: "कारण", english: "Cause", example: "What is the cause?", exampleHindi: "कारण क्या है?" },
  { hindi: "बदलाव", english: "Change", example: "Change is necessary.", exampleHindi: "बदलाव जरूरी है" },
  { hindi: "चुनाव", english: "Choice", example: "It is your choice.", exampleHindi: "यह आपकी पसंद है" },
  { hindi: "स्पष्ट", english: "Clear", example: "Everything is clear.", exampleHindi: "सब कुछ स्पष्ट है" },
  { hindi: "चालाक", english: "Clever", example: "Fox is a clever animal.", exampleHindi: "लोमड़ी एक चालाक जानवर है" },
  { hindi: "इकट्ठा करना", english: "Collect", example: "Collect the books.", exampleHindi: "किताबें इकट्ठा करें" },
  { hindi: "सामान्य", english: "Common", example: "It is a common mistake.", exampleHindi: "यह एक सामान्य गलती है" },
  { hindi: "तुलना करना", english: "Compare", example: "Don't compare yourself.", exampleHindi: "अपनी तुलना न करें" },
  { hindi: "पूरा करना", english: "Complete", example: "Complete your work.", exampleHindi: "अपना काम पूरा करें" },
  { hindi: "चिंता", english: "Concern", example: "It is a matter of concern.", exampleHindi: "यह चिंता का विषय है" },
  { hindi: "पुष्टि करना", english: "Confirm", example: "Please confirm the date.", exampleHindi: "कृपया तारीख की पुष्टि करें" },
  { hindi: "भ्रमित करना", english: "Confuse", example: "Don't confuse me.", exampleHindi: "मुझे भ्रमित मत करो" },
  { hindi: "जोड़ना", english: "Connect", example: "Connect the dots.", exampleHindi: "बिन्दुओं को जोड़ें" },
  { hindi: "नियंत्रण", english: "Control", example: "Control your feelings.", exampleHindi: "अपनी भावनाओं को नियंत्रित करें" },
  { hindi: "सही करना", english: "Correct", example: "Correct your mistakes.", exampleHindi: "अपनी गलतियों को सुधारें" },
  { hindi: "साहस", english: "Courage", example: "Have courage.", exampleHindi: "साहस रखें" },
  { hindi: "निर्माण करना", english: "Create", example: "Create something new.", exampleHindi: "कुछ नया बनाएं" },
  { hindi: "जिज्ञासु", english: "Curious", example: "Children are curious.", exampleHindi: "बच्चे जिज्ञासु होते हैं" },
  { hindi: "खतरा", english: "Danger", example: "There is danger ahead.", exampleHindi: "आगे खतरा है" },
  { hindi: "निर्णय लेना", english: "Decide", example: "Decide now.", exampleHindi: "अभी निर्णय लें" },
  { hindi: "गहरा", english: "Deep", example: "The ocean is deep.", exampleHindi: "समुद्र गहरा है" },
  { hindi: "मांग", english: "Demand", example: "There is high demand.", exampleHindi: "भारी मांग है" },
  { hindi: "निर्भर होना", english: "Depend", example: "Don't depend on others.", exampleHindi: "दूसरों पर निर्भर न रहें" },
  { hindi: "वर्णन करना", english: "Describe", example: "Describe the picture.", exampleHindi: "चित्र का वर्णन करें" },
  { hindi: "विकास करना", english: "Develop", example: "Develop your skills.", exampleHindi: "अपने कौशल का विकास करें" },
  { hindi: "अलग", english: "Different", example: "This is different.", exampleHindi: "यह अलग है" },
  { hindi: "कठिन", english: "Difficult", example: "The task is difficult.", exampleHindi: "कार्य कठिन है" },
  { hindi: "खोज करना", english: "Discover", example: "Discover new places.", exampleHindi: "नई जगहों की खोज करें" },
  { hindi: "प्रयास", english: "Effort", example: "Make an effort.", exampleHindi: "प्रयास करें" },
  { hindi: "भावना", english: "Emotion", example: "Control your emotions.", exampleHindi: "अपनी भावनाओं को नियंत्रित करें" },
  { hindi: "प्रोत्साहित करना", english: "Encourage", example: "Encourage others.", exampleHindi: "दूसरों को प्रोत्साहित करें" },
  { hindi: "ऊर्जा", english: "Energy", example: "Sun is a source of energy.", exampleHindi: "सूर्य ऊर्जा का स्रोत है" },
  { hindi: "आनंद लेना", english: "Enjoy", example: "Enjoy the party.", exampleHindi: "पार्टी का आनंद लें" },
  { hindi: "पर्याप्त", english: "Enough", example: "That is enough.", exampleHindi: "इतना काफी है" },
  { hindi: "बच निकलना", english: "Escape", example: "The bird escaped.", exampleHindi: "पक्षी बच निकला" },
  { hindi: "समझाना", english: "Explain", example: "Explain clearly.", exampleHindi: "स्पष्ट रूप से समझाएं" },
  { hindi: "व्यक्त करना", english: "Express", example: "Express your ideas.", exampleHindi: "अपने विचार व्यक्त करें" },
  { hindi: "असफल होना", english: "Fail", example: "Never fear to fail.", exampleHindi: "असफल होने से कभी न डरें" },
  { hindi: "न्यायपूर्ण", english: "Fair", example: "The decision was fair.", exampleHindi: "निर्णय न्यायपूर्ण था" },
  { hindi: "प्रसिद्ध", english: "Famous", example: "He is a famous writer.", exampleHindi: "वह एक प्रसिद्ध लेखक हैं" },
  { hindi: "डर", english: "Fear", example: "Face your fear.", exampleHindi: "अपने डर का सामना करें" },
  { hindi: "ध्यान", english: "Focus", example: "Focus on your goals.", exampleHindi: "अपने लक्ष्यों पर ध्यान दें" },
  { hindi: "पालन करना", english: "Follow", example: "Follow the rules.", exampleHindi: "नियमों का पालन करें" },
  { hindi: "बल", english: "Force", example: "Don't use force.", exampleHindi: "बल का प्रयोग न करें" },
  { hindi: "भूलना", english: "Forget", example: "Never forget the keys.", exampleHindi: "चाबियां कभी न भूलें" },
  { hindi: "आगे", english: "Forward", example: "Move forward.", exampleHindi: "आगे बढ़ें" },
  { hindi: "स्वतंत्रता", english: "Freedom", example: "Freedom is precious.", exampleHindi: "स्वतंत्रता अनमोल है" },
  { hindi: "मित्रतापूर्ण", english: "Friendly", example: "He is very friendly.", exampleHindi: "वह बहुत मिलनसार है" },
  { hindi: "भविष्य", english: "Future", example: "Think about future.", exampleHindi: "भविष्य के बारे में सोचें" },
  { hindi: "प्राप्त करना", english: "Gain", example: "Gain more knowledge.", exampleHindi: "अधिक ज्ञान प्राप्त करें" },
  { hindi: "लक्ष्य", english: "Goal", example: "Reach your goal.", exampleHindi: "अपने लक्ष्य तक पहुँचें" },
  { hindi: "बढ़ना", english: "Grow", example: "Plants grow fast.", exampleHindi: "पौधे तेजी से बढ़ते हैं" },
  { hindi: "होना", english: "Happen", example: "What will happen?", exampleHindi: "क्या होगा?" },
  { hindi: "स्वस्थ", english: "Healthy", example: "Eat healthy food.", exampleHindi: "स्वस्थ भोजन करें" },
  { hindi: "ईमानदार", english: "Honest", example: "Always be honest.", exampleHindi: "हमेशा ईमानदार रहें" },
  { hindi: "आशा", english: "Hope", example: "There is still hope.", exampleHindi: "अभी भी उम्मीद है" },
  { hindi: "विशाल", english: "Huge", example: "This is a huge building.", exampleHindi: "यह एक विशाल इमारत है" },
  { hindi: "जल्दी करना", english: "Hurry", example: "Hurry up!", exampleHindi: "जल्दी करो!" },
  { hindi: "महत्वपूर्ण", english: "Important", example: "It is important.", exampleHindi: "यह महत्वपूर्ण है" },
  { hindi: "सुधारना", english: "Improve", example: "Improve your health.", exampleHindi: "अपने स्वास्थ्य में सुधार करें" },
  { hindi: "शामिल करना", english: "Include", example: "Include everyone.", exampleHindi: "सबको शामिल करो" },
  { hindi: "बढ़ाना", english: "Increase", example: "Increase the speed.", exampleHindi: "गति बढ़ाएं" },
  { hindi: "स्वतंत्र", english: "Independent", example: "Be independent.", exampleHindi: "स्वतंत्र बनें" },
  { hindi: "प्रभाव", english: "Influence", example: "Good influence.", exampleHindi: "अच्छा प्रभाव" },
  { hindi: "सूचित करना", english: "Inform", example: "Inform the police.", exampleHindi: "पुलिस को सूचित करें" },
  { hindi: "बुद्धिमान", english: "Intelligent", example: "He is intelligent.", exampleHindi: "वह बुद्धिमान है" },
  { hindi: "रुचि", english: "Interest", example: "Show interest.", exampleHindi: "रुचि दिखाएं" },
  { hindi: "यात्रा", english: "Journey", example: "Save journey.", exampleHindi: "सुरक्षित यात्रा" },
  { hindi: "न्याय", english: "Justice", example: "We need justice.", exampleHindi: "हमें न्याय चाहिए" },
  { hindi: "ज्ञान", english: "Knowledge", example: "Power is knowledge.", exampleHindi: "शक्ति ज्ञान है" },
  { hindi: "नेता", english: "Leader", example: "He is a leader.", exampleHindi: "वह एक नेता है" },
  { hindi: "सीखना", english: "Learn", example: "Learn every day.", exampleHindi: "हर रोज सीखें" },
  { hindi: "सीमा", english: "Limit", example: "Know your limit.", exampleHindi: "अपनी सीमा जानें" },
  { hindi: "प्रबंध करना", english: "Manage", example: "Manage your expense.", exampleHindi: "अपने खर्च का प्रबंधन करें" },
  { hindi: "अर्थ", english: "Meaning", example: "What is meaning?", exampleHindi: "अर्थ क्या है?" },
  { hindi: "याददाश्त", english: "Memory", example: "Good memory.", exampleHindi: "अच्छी याददाश्त" },
  { hindi: "गलती", english: "Mistake", example: "Don't repeat mistake.", exampleHindi: "गलती न दोहराएं" },
  { hindi: "आधुनिक", english: "Modern", example: "Modern technology.", exampleHindi: "आधुनिक तकनीक" },

  // Remaining existing words (Level 3 onwards)
  { hindi: "आसान", english: "Easy", example: "This is easy.", exampleHindi: "यह आसान है" },
  { hindi: "महत्वपूर्ण", english: "Important", example: "This is important.", exampleHindi: "यह महत्वपूर्ण है" },
  { hindi: "विशेष", english: "Special", example: "Today is special.", exampleHindi: "आज खास है" },
  { hindi: "अलग", english: "Different", example: "This is different.", exampleHindi: "यह अलग है" },
  { hindi: "समान", english: "Same", example: "We are same.", exampleHindi: "हम समान हैं" },
  { hindi: "कोशिश करना", english: "Try", example: "Try your best.", exampleHindi: "पूरी कोशिश करो" },
  { hindi: "जांच करना", english: "Check", example: "Check your answer.", exampleHindi: "उत्तर जांचो" },
  { hindi: "सही करना", english: "Correct", example: "Correct mistake.", exampleHindi: "गलती सुधारो" },
  { hindi: "गलती", english: "Mistake", example: "Learn from mistake.", exampleHindi: "गलती से सीखो" },
  { hindi: "पूछना", english: "Ask", example: "Ask teacher.", exampleHindi: "शिक्षक से पूछो" },
  { hindi: "उत्तर देना", english: "Answer", example: "Answer quickly.", exampleHindi: "जल्दी उत्तर दो" },
  { hindi: "बोलना", english: "Speak", example: "Speak English.", exampleHindi: "अंग्रेजी बोलो" },
  { hindi: "सुनना", english: "Listen", example: "Listen carefully.", exampleHindi: "ध्यान से सुनो" },
  { hindi: "समझना", english: "Understand", example: "I understand.", exampleHindi: "मैं समझता हूँ" },
  { hindi: "सोचना", english: "Think", example: "Think before speaking.", exampleHindi: "सोचकर बोलो" },
  { hindi: "जानना", english: "Know", example: "I know this.", exampleHindi: "मैं जानता हूँ" },
  { hindi: "सीखना", english: "Learn", example: "Learn words.", exampleHindi: "शब्द सीखो" },
  { hindi: "सिखाना", english: "Teach", example: "He teaches well.", exampleHindi: "वह अच्छा सिखाता है" },
  { hindi: "उपयोग करना", english: "Use", example: "Use this word.", exampleHindi: "इस शब्द का उपयोग करो" },
  { hindi: "बनाना", english: "Create", example: "Create something.", exampleHindi: "कुछ बनाओ" },
  { hindi: "निर्माण करना", english: "Build", example: "Build future.", exampleHindi: "भविष्य बनाओ" },
  { hindi: "विकसित करना", english: "Develop", example: "Develop skills.", exampleHindi: "skills विकसित करो" },
  { hindi: "सुधारना", english: "Improve", example: "Improve daily.", exampleHindi: "रोज सुधार करो" },
  { hindi: "ध्यान देना", english: "Focus", example: "Focus on study.", exampleHindi: "पढ़ाई पर ध्यान दो" },
  { hindi: "ध्यान", english: "Attention", example: "Pay attention.", exampleHindi: "ध्यान दो" },
  { hindi: "प्रयास", english: "Effort", example: "Put effort.", exampleHindi: "प्रयास करो" },
  { hindi: "ऊर्जा", english: "Energy", example: "Save energy.", exampleHindi: "ऊर्जा बचाओ" },
  { hindi: "समय", english: "Time", example: "Time is important.", exampleHindi: "समय महत्वपूर्ण है" },
  { hindi: "मौका", english: "Chance", example: "Take chance.", exampleHindi: "मौका लो" },
  { hindi: "आत्मविश्वासी", english: "Confident", example: "She is confident.", exampleHindi: "वह आत्मविश्वासी है" },
  { hindi: "अभ्यास करना", english: "Practice", example: "Practice daily.", exampleHindi: "रोज अभ्यास करो" },
  { hindi: "गलती", english: "Mistake", example: "Learn from mistakes.", exampleHindi: "गलतियों से सीखो" },
  { hindi: "अवसर", english: "Opportunity", example: "This is a good opportunity.", exampleHindi: "यह अच्छा अवसर है" },
  { hindi: "अनुभव", english: "Experience", example: "Experience is important.", exampleHindi: "अनुभव महत्वपूर्ण है" },
  { hindi: "ज्ञान", english: "Knowledge", example: "Knowledge is power.", exampleHindi: "ज्ञान शक्ति है" },
  { hindi: "कौशल", english: "Skill", example: "Improve your skill.", exampleHindi: "अपना कौशल सुधारो" },
  { hindi: "प्रतिभा", english: "Talent", example: "He has talent.", exampleHindi: "उसमें प्रतिभा है" },
  { hindi: "सफलता", english: "Success", example: "Success needs effort.", exampleHindi: "सफलता के लिए प्रयास चाहिए" },
  { hindi: "असफलता", english: "Failure", example: "Failure teaches lessons.", exampleHindi: "असफलता सिखाती है" },
  { hindi: "प्रबंधित करना", english: "Manage", example: "Manage your time.", exampleHindi: "अपना समय संभालो" },
  { hindi: "नियंत्रण करना", english: "Control", example: "Control your anger.", exampleHindi: "गुस्सा नियंत्रित करो" },
  { hindi: "सुधारना", english: "Improve", example: "Improve your English.", exampleHindi: "अपनी अंग्रेजी सुधारो" },
  { hindi: "विकसित करना", english: "Develop", example: "Develop your skills.", exampleHindi: "अपनी skills विकसित करो" },
  { hindi: "बनाना", english: "Create", example: "Create something new.", exampleHindi: "कुछ नया बनाओ" },
  { hindi: "डिज़ाइन करना", english: "Design", example: "Design a project.", exampleHindi: "प्रोजेक्ट डिजाइन करो" },
  { hindi: "निर्माण करना", english: "Build", example: "Build your future.", exampleHindi: "अपना भविष्य बनाओ" },
  { hindi: "योजना बनाना", english: "Plan", example: "Plan your day.", exampleHindi: "दिन की योजना बनाओ" },
  { hindi: "व्यवस्थित करना", english: "Organize", example: "Organize your work.", exampleHindi: "काम व्यवस्थित करो" },
  { hindi: "पूरा करना", english: "Complete", example: "Complete your task.", exampleHindi: "काम पूरा करो" },
  { hindi: "निर्णय", english: "Decision", example: "Make a decision.", exampleHindi: "निर्णय लो" },
  { hindi: "चयन", english: "Choice", example: "This is your choice.", exampleHindi: "यह तुम्हारी पसंद है" },
  { hindi: "कारण", english: "Reason", example: "Give a reason.", exampleHindi: "कारण बताओ" },
  { hindi: "परिणाम", english: "Result", example: "The result is good.", exampleHindi: "परिणाम अच्छा है" },
  { hindi: "प्रगति", english: "Progress", example: "Track your progress.", exampleHindi: "प्रगति देखो" },
  { hindi: "प्रयास", english: "Effort", example: "Put effort.", exampleHindi: "प्रयास करो" },
  { hindi: "ऊर्जा", english: "Energy", example: "Use your energy.", exampleHindi: "ऊर्जा का उपयोग करो" },
  { hindi: "ध्यान देना", english: "Focus", example: "Focus on study.", exampleHindi: "पढ़ाई पर ध्यान दो" },
  { hindi: "ध्यान", english: "Attention", example: "Pay attention.", exampleHindi: "ध्यान दो" },
  { hindi: "समय", english: "Time", example: "Time is valuable.", exampleHindi: "समय की कद्र करो" },
  { hindi: "सुधारना", english: "Improve", example: "Improve daily.", exampleHindi: "रोज सुधार करो" },
  { hindi: "सीखना", english: "Learn", example: "Learn new things.", exampleHindi: "नई चीजें सीखो" },
  { hindi: "सिखाना", english: "Teach", example: "He teaches well.", exampleHindi: "वह अच्छा सिखाता है" },
  { hindi: "समझाना", english: "Explain", example: "Explain clearly.", exampleHindi: "साफ समझाओ" },
  { hindi: "चर्चा करना", english: "Discuss", example: "Discuss the topic.", exampleHindi: "विषय पर चर्चा करो" },
  { hindi: "हल करना", english: "Solve", example: "Solve the problem.", exampleHindi: "समस्या हल करो" },
  { hindi: "जांच करना", english: "Check", example: "Check your work.", exampleHindi: "काम जांचो" },
  { hindi: "सही करना", english: "Correct", example: "Correct your mistake.", exampleHindi: "गलती सुधारो" },
  { hindi: "कोशिश करना", english: "Try", example: "Try again.", exampleHindi: "फिर कोशिश करो" },
  { hindi: "प्राप्त करना", english: "Achieve", example: "Achieve your goal.", exampleHindi: "लक्ष्य प्राप्त करो" },
  { hindi: "विश्वास करना", english: "Believe", example: "Believe in yourself.", exampleHindi: "खुद पर विश्वास करो" },
  { hindi: "सोचना", english: "Think", example: "Think wisely.", exampleHindi: "समझदारी से सोचो" },
  { hindi: "समझना", english: "Understand", example: "I understand now.", exampleHindi: "अब समझ गया" },
  { hindi: "याद रखना", english: "Remember", example: "Remember this.", exampleHindi: "इसे याद रखो" },
  { hindi: "भूलना", english: "Forget", example: "Don’t forget.", exampleHindi: "मत भूलो" },
  { hindi: "बोलना", english: "Speak", example: "Speak clearly.", exampleHindi: "साफ बोलो" },
  { hindi: "सुनना", english: "Listen", example: "Listen carefully.", exampleHindi: "ध्यान से सुनो" },
  { hindi: "पढ़ना", english: "Read", example: "Read daily.", exampleHindi: "रोज पढ़ो" },
  { hindi: "लिखना", english: "Write", example: "Write neatly.", exampleHindi: "साफ लिखो" },
  { hindi: "उपयोग करना", english: "Use", example: "Use this word.", exampleHindi: "इस शब्द का उपयोग करो" },
  { hindi: "शुरू करना", english: "Start", example: "Start now.", exampleHindi: "अभी शुरू करो" },
  { hindi: "खत्म करना", english: "Finish", example: "Finish fast.", exampleHindi: "जल्दी खत्म करो" },
  { hindi: "जारी रखना", english: "Continue", example: "Continue learning.", exampleHindi: "सीखना जारी रखो" },
  { hindi: "रोकना", english: "Stop", example: "Stop here.", exampleHindi: "यहाँ रुक जाओ" },
  { hindi: "इंतजार करना", english: "Wait", example: "Wait a moment.", exampleHindi: "थोड़ा इंतजार करो" },
  { hindi: "मदद करना", english: "Help", example: "Help others.", exampleHindi: "दूसरों की मदद करो" },
  { hindi: "समर्थन करना", english: "Support", example: "Support your team.", exampleHindi: "टीम का समर्थन करो" },
  { hindi: "नेतृत्व करना", english: "Lead", example: "Lead the group.", exampleHindi: "समूह का नेतृत्व करो" },
  { hindi: "अनुसरण करना", english: "Follow", example: "Follow rules.", exampleHindi: "नियमों का पालन करो" },
  { hindi: "जीतना", english: "Win", example: "Win the game.", exampleHindi: "खेल जीतो" },
  { hindi: "हारना", english: "Lose", example: "Don’t lose hope.", exampleHindi: "उम्मीद मत हारो" },
  { hindi: "कोशिश करना", english: "Try", example: "Try your best.", exampleHindi: "पूरी कोशिश करो" },
  { hindi: "सुधारना", english: "Improve", example: "Improve fast.", exampleHindi: "जल्दी सुधार करो" },
  { hindi: "बढ़ना", english: "Grow", example: "Grow daily.", exampleHindi: "रोज बढ़ो" },
  { hindi: "बदलना", english: "Change", example: "Change yourself.", exampleHindi: "खुद को बदलो" },
  { hindi: "सीखना", english: "Learn", example: "Learn English.", exampleHindi: "अंग्रेजी सीखो" },
  { hindi: "अभ्यास करना", english: "Practice", example: "Practice more.", exampleHindi: "ज्यादा अभ्यास करो" },
  { hindi: "दोहराना", english: "Repeat", example: "Repeat again.", exampleHindi: "फिर दोहराओ" },
  { hindi: "ध्यान देना", english: "Focus", example: "Stay focused.", exampleHindi: "ध्यान बनाए रखो" },
  { hindi: "हासिल करना", english: "Achieve", example: "Achieve success.", exampleHindi: "सफलता हासिल करो" },
  { hindi: "समझदार", english: "Smart", example: "Be smart.", exampleHindi: "समझदार बनो" },
  { hindi: "मजबूत", english: "Strong", example: "Stay strong.", exampleHindi: "मजबूत रहो" },
  { hindi: "कमजोर", english: "Weak", example: "Don’t be weak.", exampleHindi: "कमजोर मत बनो" },
  { hindi: "सक्रिय", english: "Active", example: "Stay active.", exampleHindi: "सक्रिय रहो" },
  { hindi: "आलसी", english: "Lazy", example: "Don’t be lazy.", exampleHindi: "आलसी मत बनो" },
  { hindi: "तेज", english: "Quick", example: "Be quick.", exampleHindi: "तेज बनो" },
  { hindi: "धीमा", english: "Slow", example: "Don’t be slow.", exampleHindi: "धीमे मत बनो" },
  { hindi: "साफ", english: "Clear", example: "Keep it clear.", exampleHindi: "साफ रखो" },
  { hindi: "सरल", english: "Simple", example: "Keep it simple.", exampleHindi: "सरल रखो" },
  { hindi: "कठिन", english: "Difficult", example: "This is difficult.", exampleHindi: "यह कठिन है" },
  { hindi: "महत्वपूर्ण", english: "Important", example: "This is important.", exampleHindi: "यह महत्वपूर्ण है" },
  { hindi: "उपयोगी", english: "Useful", example: "This is useful.", exampleHindi: "यह उपयोगी है" },
  { hindi: "सहायक", english: "Helpful", example: "This is helpful.", exampleHindi: "यह सहायक है" },
  { hindi: "आसान", english: "Easy", example: "This is easy.", exampleHindi: "यह आसान है" },
  { hindi: "कठिन", english: "Hard", example: "Work hard.", exampleHindi: "मेहनत करो" },
  { hindi: "सही", english: "Right", example: "This is right.", exampleHindi: "यह सही है" },
  { hindi: "गलत", english: "Wrong", example: "This is wrong.", exampleHindi: "यह गलत है" },
  { hindi: "सबसे अच्छा", english: "Best", example: "Do your best.", exampleHindi: "अपना सर्वश्रेष्ठ करो" },
  { hindi: "बेहतर", english: "Better", example: "Do better.", exampleHindi: "बेहतर करो" },
  { hindi: "अच्छा", english: "Good", example: "Good job.", exampleHindi: "अच्छा काम" },
  { hindi: "बुरा", english: "Bad", example: "Bad habit.", exampleHindi: "बुरी आदत" },
  { hindi: "नया", english: "New", example: "Learn new words.", exampleHindi: "नए शब्द सीखो" },
  { hindi: "पुराना", english: "Old", example: "This is old.", exampleHindi: "यह पुराना है" },
  { hindi: "ऊंचा", english: "High", example: "High goal.", exampleHindi: "ऊंचा लक्ष्य" },
  { hindi: "नीचा", english: "Low", example: "Low score.", exampleHindi: "कम अंक" },
  { hindi: "जल्दी", english: "Early", example: "Wake early.", exampleHindi: "जल्दी उठो" },
  { hindi: "देर", english: "Late", example: "Don’t be late.", exampleHindi: "देर मत करो" },
  { hindi: "आज", english: "Today", example: "Study today.", exampleHindi: "आज पढ़ो" },
  { hindi: "कल", english: "Tomorrow", example: "Do tomorrow.", exampleHindi: "कल करो" },
];
