export const WORD_LIST = [
  { hindi: "खाना", english: "Eat", example: "I eat food daily.", exampleHindi: "मैं रोज खाना खाता हूँ" },
  { hindi: "जाना", english: "Go", example: "I go to school.", exampleHindi: "मैं स्कूल जाता हूँ" },
  { hindi: "आना", english: "Come", example: "Please come here.", exampleHindi: "कृपया यहाँ आओ" },
  { hindi: "बनाना", english: "Make", example: "I make a cake.", exampleHindi: "मैं केक बनाता हूँ" },
  { hindi: "लेना", english: "Take", example: "Take this book.", exampleHindi: "यह किताब लो" },
  { hindi: "देना", english: "Give", example: "Give me water.", exampleHindi: "मुझे पानी दो" },
  { hindi: "दौड़ना", english: "Run", example: "He runs fast.", exampleHindi: "वह तेज दौड़ता है" },
  { hindi: "पढ़ना", english: "Read", example: "I read a book.", exampleHindi: "मैं किताब पढ़ता हूँ" },
  { hindi: "लिखना", english: "Write", example: "Write your name.", exampleHindi: "अपना नाम लिखो" },
  { hindi: "बोलना", english: "Speak", example: "Speak clearly.", exampleHindi: "साफ बोलो" },
  { hindi: "पानी", english: "Water", example: "Drink water.", exampleHindi: "पानी पियो" },
  { hindi: "खाना", english: "Food", example: "Food is ready.", exampleHindi: "खाना तैयार है" },
  { hindi: "किताब", english: "Book", example: "This is my book.", exampleHindi: "यह मेरी किताब है" },
  { hindi: "कलम", english: "Pen", example: "I have a pen.", exampleHindi: "मेरे पास कलम है" },
  { hindi: "स्कूल", english: "School", example: "My school is big.", exampleHindi: "मेरा स्कूल बड़ा है" },
  { hindi: "खुश", english: "Happy", example: "I am happy.", exampleHindi: "मैं खुश हूँ" },
  { hindi: "दुखी", english: "Sad", example: "She is sad.", exampleHindi: "वह दुखी है" },
  { hindi: "बड़ा", english: "Big", example: "This is a big house.", exampleHindi: "यह बड़ा घर है" },
  { hindi: "छोटा", english: "Small", example: "This is a small cat.", exampleHindi: "यह छोटी बिल्ली है" },
  { hindi: "अच्छा", english: "Good", example: "This is good.", exampleHindi: "यह अच्छा है" },
  { hindi: "बुरा", english: "Bad", example: "This is bad.", exampleHindi: "यह बुरा है" },
  { hindi: "तेज", english: "Fast", example: "He is fast.", exampleHindi: "वह तेज है" },
  { hindi: "धीमा", english: "Slow", example: "The turtle is slow.", exampleHindi: "कछुआ धीमा है" },
  { hindi: "गरम", english: "Hot", example: "Tea is hot.", exampleHindi: "चाय गरम है" },
  { hindi: "ठंडा", english: "Cold", example: "Water is cold.", exampleHindi: "पानी ठंडा है" },
  { hindi: "दिन", english: "Day", example: "Today is a good day.", exampleHindi: "आज अच्छा दिन है" },
  { hindi: "रात", english: "Night", example: "It is night now.", exampleHindi: "अब रात है" },
  { hindi: "दोस्त", english: "Friend", example: "He is my friend.", exampleHindi: "वह मेरा दोस्त है" },
  { hindi: "परिवार", english: "Family", example: "I love my family.", exampleHindi: "मैं अपने परिवार से प्यार करता हूँ" },
  { hindi: "घर", english: "Home", example: "I am at home.", exampleHindi: "मैं घर पर हूँ" },
  { hindi: "पहले", english: "Before", example: "Wash hands before eating.", exampleHindi: "खाने से पहले हाथ धोओ" },
  { hindi: "बाद में", english: "After", example: "Come after lunch.", exampleHindi: "खाने के बाद आओ" },
  { hindi: "हमेशा", english: "Always", example: "I always help others.", exampleHindi: "मैं हमेशा मदद करता हूँ" },
  { hindi: "कभी नहीं", english: "Never", example: "I never lie.", exampleHindi: "मैं कभी झूठ नहीं बोलता" },
  { hindi: "कभी-कभी", english: "Sometimes", example: "I sometimes play.", exampleHindi: "मैं कभी-कभी खेलता हूँ" },
  { hindi: "शिक्षक", english: "Teacher", example: "My teacher is kind.", exampleHindi: "मेरे शिक्षक दयालु हैं" },
  { hindi: "विद्यार्थी", english: "Student", example: "I am a student.", exampleHindi: "मैं विद्यार्थी हूँ" },
  { hindi: "कक्षा", english: "Class", example: "My class is clean.", exampleHindi: "मेरी कक्षा साफ है" },
  { hindi: "खोलना", english: "Open", example: "Open the door.", exampleHindi: "दरवाजा खोलो" },
  { hindi: "बंद करना", english: "Close", example: "Close the window.", exampleHindi: "खिड़की बंद करो" },
  { hindi: "शुरू करना", english: "Start", example: "Start your work.", exampleHindi: "काम शुरू करो" },
  { hindi: "खत्म करना", english: "Finish", example: "Finish homework.", exampleHindi: "होमवर्क खत्म करो" },
  { hindi: "सीखना", english: "Learn", example: "I learn English.", exampleHindi: "मैं अंग्रेजी सीखता हूँ" },
  { hindi: "सिखाना", english: "Teach", example: "She teaches math.", exampleHindi: "वह गणित सिखाती है" },
  { hindi: "पूछना", english: "Ask", example: "Ask a question.", exampleHindi: "सवाल पूछो" },
  { hindi: "उत्तर देना", english: "Answer", example: "Answer correctly.", exampleHindi: "सही उत्तर दो" },
  { hindi: "समझना", english: "Understand", example: "I understand this.", exampleHindi: "मैं इसे समझता हूँ" },
  { hindi: "भूलना", english: "Forget", example: "Don’t forget.", exampleHindi: "मत भूलो" },
  { hindi: "साफ करना", english: "Clean", example: "Clean your room.", exampleHindi: "कमरा साफ करो" },
  { hindi: "गंदा", english: "Dirty", example: "The floor is dirty.", exampleHindi: "फर्श गंदा है" },
  { hindi: "सुंदर", english: "Beautiful", example: "The flower is beautiful.", exampleHindi: "फूल सुंदर है" },
  { hindi: "बदसूरत", english: "Ugly", example: "This is ugly.", exampleHindi: "यह बदसूरत है" },
  { hindi: "आसान", english: "Easy", example: "This is easy.", exampleHindi: "यह आसान है" },
  { hindi: "कठिन", english: "Difficult", example: "This is difficult.", exampleHindi: "यह कठिन है" },
  { hindi: "पास", english: "Near", example: "The shop is near.", exampleHindi: "दुकान पास है" },
  { hindi: "दूर", english: "Far", example: "The school is far.", exampleHindi: "स्कूल दूर है" },
  { hindi: "सही", english: "Right", example: "Your answer is right.", exampleHindi: "जवाब सही है" },
  { hindi: "गलत", english: "Wrong", example: "This is wrong.", exampleHindi: "यह गलत है" },
  { hindi: "जल्दी", english: "Early", example: "Wake up early.", exampleHindi: "जल्दी उठो" },
  { hindi: "देर", english: "Late", example: "Don’t be late.", exampleHindi: "देर मत करो" },
  { hindi: "आज", english: "Today", example: "Today is Sunday.", exampleHindi: "आज रविवार है" },
  { hindi: "कल", english: "Tomorrow", example: "Tomorrow is holiday.", exampleHindi: "कल छुट्टी है" },
  { hindi: "कल", english: "Yesterday", example: "Yesterday was fun.", exampleHindi: "कल मजेदार था" },
  { hindi: "खरीदना", english: "Buy", example: "I buy fruits.", exampleHindi: "मैं फल खरीदता हूँ" },
  { hindi: "बेचना", english: "Sell", example: "He sells vegetables.", exampleHindi: "वह सब्जी बेचता है" },
  { hindi: "लाना", english: "Bring", example: "Bring water.", exampleHindi: "पानी लाओ" },
  { hindi: "भेजना", english: "Send", example: "Send message.", exampleHindi: "संदेश भेजो" },
  { hindi: "फोन करना", english: "Call", example: "Call me later.", exampleHindi: "बाद में कॉल करो" },
  { hindi: "खेलना", english: "Play", example: "I play football.", exampleHindi: "मैं फुटबॉल खेलता हूँ" },
  { hindi: "काम करना", english: "Work", example: "I work hard.", exampleHindi: "मैं मेहनत करता हूँ" },
  { hindi: "आराम करना", english: "Rest", example: "Take rest.", exampleHindi: "आराम करो" },
  { hindi: "सोना", english: "Sleep", example: "I sleep early.", exampleHindi: "मैं जल्दी सोता हूँ" },
  { hindi: "जागना", english: "Wake", example: "Wake up now.", exampleHindi: "अब जागो" },
  { hindi: "प्यार करना", english: "Love", example: "I love my parents.", exampleHindi: "मैं माता-पिता से प्यार करता हूँ" },
  { hindi: "पसंद करना", english: "Like", example: "I like mango.", exampleHindi: "मुझे आम पसंद है" },
  { hindi: "नफरत करना", english: "Hate", example: "I hate lies.", exampleHindi: "मुझे झूठ से नफरत है" },
  { hindi: "मदद करना", english: "Help", example: "Help me.", exampleHindi: "मेरी मदद करो" },
  { hindi: "कोशिश करना", english: "Try", example: "Try again.", exampleHindi: "फिर कोशिश करो" },
  { hindi: "सुधारना", english: "Improve", example: "I want to improve my English.", exampleHindi: "मैं अंग्रेजी सुधारना चाहता हूँ" },
  { hindi: "निर्णय लेना", english: "Decide", example: "I decide my future.", exampleHindi: "मैं अपना भविष्य तय करता हूँ" },
  { hindi: "समझाना", english: "Explain", example: "Please explain this.", exampleHindi: "इसे समझाओ" },
  { hindi: "चर्चा करना", english: "Discuss", example: "We discuss problems.", exampleHindi: "हम चर्चा करते हैं" },
  { hindi: "चुनना", english: "Choose", example: "Choose the answer.", exampleHindi: "उत्तर चुनो" },
  { hindi: "समस्या", english: "Problem", example: "This is a problem.", exampleHindi: "यह समस्या है" },
  { hindi: "समाधान", english: "Solution", example: "Find solution.", exampleHindi: "समाधान ढूंढो" },
  { hindi: "कारण", english: "Reason", example: "Tell the reason.", exampleHindi: "कारण बताओ" },
  { hindi: "परिणाम", english: "Result", example: "Result is good.", exampleHindi: "परिणाम अच्छा है" },
  { hindi: "लक्ष्य", english: "Goal", example: "My goal is success.", exampleHindi: "मेरा लक्ष्य सफलता है" },
  { hindi: "योजना बनाना", english: "Plan", example: "Make a plan.", exampleHindi: "योजना बनाओ" },
  { hindi: "तैयार करना", english: "Prepare", example: "Prepare for exam.", exampleHindi: "परीक्षा की तैयारी करो" },
  { hindi: "अभ्यास करना", english: "Practice", example: "Practice daily.", exampleHindi: "रोज अभ्यास करो" },
  { hindi: "दोहराना", english: "Repeat", example: "Repeat again.", exampleHindi: "फिर दोहराओ" },
  { hindi: "याद रखना", english: "Remember", example: "Remember this.", exampleHindi: "इसे याद रखो" },
  { hindi: "भूलना", english: "Forget", example: "Don’t forget.", exampleHindi: "मत भूलो" },
  { hindi: "विश्वास करना", english: "Believe", example: "Believe yourself.", exampleHindi: "खुद पर विश्वास करो" },
  { hindi: "प्राप्त करना", english: "Achieve", example: "Achieve success.", exampleHindi: "सफलता पाओ" },
  { hindi: "असफल होना", english: "Fail", example: "Don’t fail.", exampleHindi: "असफल मत हो" },
  { hindi: "सफलता", english: "Success", example: "Success comes.", exampleHindi: "सफलता आती है" },
  { hindi: "मेहनती", english: "Hard", example: "Work hard.", exampleHindi: "मेहनत करो" },
  { hindi: "आसान", english: "Easy", example: "This is easy.", exampleHindi: "यह आसान है" },
  { hindi: "महत्वपूर्ण", english: "Important", example: "This is important.", exampleHindi: "यह महत्वपूर्ण है" },
  { hindi: "विशेष", english: "Special", example: "Today is special.", exampleHindi: "आज खास है" },
  { hindi: "अलग", english: "Different", example: "This is different.", exampleHindi: "यह अलग है" },
  { hindi: "समान", english: "Same", example: "We are same.", exampleHindi: "हम समान हैं" },
  { hindi: "कोशिश करना", english: "Try", example: "Try your best.", exampleHindi: "पूरी कोशिश करो" },
  { hindi: "जांच करना", english: "Check", example: "Check your answer.", exampleHindi: "उत्तर जांचो" },
  { hindi: "सही करना", english: "Correct", example: "Correct mistake.", exampleHindi: "गलती सुधारो" },
  { hindi: "गलती", english: "Mistake", example: "Learn from mistake.", exampleHindi: "गलती से सीखो" },
  { hindi: "पूछना", english: "Ask", example: "Ask teacher.", exampleHindi: "शिक्षक से पूछो" },
  { hindi: "उत्तर देना", english: "Answer", example: "Answer quickly.", exampleHindi: "जल्दी उत्तर दो" },
  { hindi: "बोलना", english: "Speak", example: "Speak English.", exampleHindi: "अंग्रेजी बोलो" },
  { hindi: "सुनना", english: "Listen", example: "Listen carefully.", exampleHindi: "ध्यान से सुनो" },
  { hindi: "समझना", english: "Understand", example: "I understand.", exampleHindi: "मैं समझता हूँ" },
  { hindi: "सोचना", english: "Think", example: "Think before speaking.", exampleHindi: "सोचकर बोलो" },
  { hindi: "जानना", english: "Know", example: "I know this.", exampleHindi: "मैं जानता हूँ" },
  { hindi: "सीखना", english: "Learn", example: "Learn words.", exampleHindi: "शब्द सीखो" },
  { hindi: "सिखाना", english: "Teach", example: "He teaches well.", exampleHindi: "वह अच्छा सिखाता है" },
  { hindi: "उपयोग करना", english: "Use", example: "Use this word.", exampleHindi: "इस शब्द का उपयोग करो" },
  { hindi: "बनाना", english: "Create", example: "Create something.", exampleHindi: "कुछ बनाओ" },
  { hindi: "निर्माण करना", english: "Build", example: "Build future.", exampleHindi: "भविष्य बनाओ" },
  { hindi: "विकसित करना", english: "Develop", example: "Develop skills.", exampleHindi: "skills विकसित करो" },
  { hindi: "सुधारना", english: "Improve", example: "Improve daily.", exampleHindi: "रोज सुधार करो" },
  { hindi: "ध्यान देना", english: "Focus", example: "Focus on study.", exampleHindi: "पढ़ाई पर ध्यान दो" },
  { hindi: "ध्यान", english: "Attention", example: "Pay attention.", exampleHindi: "ध्यान दो" },
  { hindi: "प्रयास", english: "Effort", example: "Put effort.", exampleHindi: "प्रयास करो" },
  { hindi: "ऊर्जा", english: "Energy", example: "Save energy.", exampleHindi: "ऊर्जा बचाओ" },
  { hindi: "समय", english: "Time", example: "Time is important.", exampleHindi: "समय महत्वपूर्ण है" },
  { hindi: "मौका", english: "Chance", example: "Take chance.", exampleHindi: "मौका लो" },
  { hindi: "आत्मविश्वासी", english: "Confident", example: "She is confident.", exampleHindi: "वह आत्मविश्वासी है" },
  { hindi: "अभ्यास करना", english: "Practice", example: "Practice daily.", exampleHindi: "रोज अभ्यास करो" },
  { hindi: "गलती", english: "Mistake", example: "Learn from mistakes.", exampleHindi: "गलतियों से सीखो" },
  { hindi: "अवसर", english: "Opportunity", example: "This is a good opportunity.", exampleHindi: "यह अच्छा अवसर है" },
  { hindi: "अनुभव", english: "Experience", example: "Experience is important.", exampleHindi: "अनुभव महत्वपूर्ण है" },
  { hindi: "ज्ञान", english: "Knowledge", example: "Knowledge is power.", exampleHindi: "ज्ञान शक्ति है" },
  { hindi: "कौशल", english: "Skill", example: "Improve your skill.", exampleHindi: "अपना कौशल सुधारो" },
  { hindi: "प्रतिभा", english: "Talent", example: "He has talent.", exampleHindi: "उसमें प्रतिभा है" },
  { hindi: "सफलता", english: "Success", example: "Success needs effort.", exampleHindi: "सफलता के लिए प्रयास चाहिए" },
  { hindi: "असफलता", english: "Failure", example: "Failure teaches lessons.", exampleHindi: "असफलता सिखाती है" },
  { hindi: "प्रबंधित करना", english: "Manage", example: "Manage your time.", exampleHindi: "अपना समय संभालो" },
  { hindi: "नियंत्रण करना", english: "Control", example: "Control your anger.", exampleHindi: "गुस्सा नियंत्रित करो" },
  { hindi: "सुधारना", english: "Improve", example: "Improve your English.", exampleHindi: "अपनी अंग्रेजी सुधारो" },
  { hindi: "विकसित करना", english: "Develop", example: "Develop your skills.", exampleHindi: "अपनी skills विकसित करो" },
  { hindi: "बनाना", english: "Create", example: "Create something new.", exampleHindi: "कुछ नया बनाओ" },
  { hindi: "डिज़ाइन करना", english: "Design", example: "Design a project.", exampleHindi: "प्रोजेक्ट डिजाइन करो" },
  { hindi: "निर्माण करना", english: "Build", example: "Build your future.", exampleHindi: "अपना भविष्य बनाओ" },
  { hindi: "योजना बनाना", english: "Plan", example: "Plan your day.", exampleHindi: "दिन की योजना बनाओ" },
  { hindi: "व्यवस्थित करना", english: "Organize", example: "Organize your work.", exampleHindi: "काम व्यवस्थित करो" },
  { hindi: "पूरा करना", english: "Complete", example: "Complete your task.", exampleHindi: "काम पूरा करो" },
  { hindi: "निर्णय", english: "Decision", example: "Make a decision.", exampleHindi: "निर्णय लो" },
  { hindi: "चयन", english: "Choice", example: "This is your choice.", exampleHindi: "यह तुम्हारी पसंद है" },
  { hindi: "कारण", english: "Reason", example: "Give a reason.", exampleHindi: "कारण बताओ" },
  { hindi: "परिणाम", english: "Result", example: "The result is good.", exampleHindi: "परिणाम अच्छा है" },
  { hindi: "प्रगति", english: "Progress", example: "Track your progress.", exampleHindi: "प्रगति देखो" },
  { hindi: "प्रयास", english: "Effort", example: "Put effort.", exampleHindi: "प्रयास करो" },
  { hindi: "ऊर्जा", english: "Energy", example: "Use your energy.", exampleHindi: "ऊर्जा का उपयोग करो" },
  { hindi: "ध्यान देना", english: "Focus", example: "Focus on study.", exampleHindi: "पढ़ाई पर ध्यान दो" },
  { hindi: "ध्यान", english: "Attention", example: "Pay attention.", exampleHindi: "ध्यान दो" },
  { hindi: "समय", english: "Time", example: "Time is valuable.", exampleHindi: "समय की कद्र करो" },
  { hindi: "सुधारना", english: "Improve", example: "Improve daily.", exampleHindi: "रोज सुधार करो" },
  { hindi: "सीखना", english: "Learn", example: "Learn new things.", exampleHindi: "नई चीजें सीखो" },
  { hindi: "सिखाना", english: "Teach", example: "He teaches well.", exampleHindi: "वह अच्छा सिखाता है" },
  { hindi: "समझाना", english: "Explain", example: "Explain clearly.", exampleHindi: "साफ समझाओ" },
  { hindi: "चर्चा करना", english: "Discuss", example: "Discuss the topic.", exampleHindi: "विषय पर चर्चा करो" },
  { hindi: "हल करना", english: "Solve", example: "Solve the problem.", exampleHindi: "समस्या हल करो" },
  { hindi: "जांच करना", english: "Check", example: "Check your work.", exampleHindi: "काम जांचो" },
  { hindi: "सही करना", english: "Correct", example: "Correct your mistake.", exampleHindi: "गलती सुधारो" },
  { hindi: "कोशिश करना", english: "Try", example: "Try again.", exampleHindi: "फिर कोशिश करो" },
  { hindi: "प्राप्त करना", english: "Achieve", example: "Achieve your goal.", exampleHindi: "लक्ष्य प्राप्त करो" },
  { hindi: "विश्वास करना", english: "Believe", example: "Believe in yourself.", exampleHindi: "खुद पर विश्वास करो" },
  { hindi: "सोचना", english: "Think", example: "Think wisely.", exampleHindi: "समझदारी से सोचो" },
  { hindi: "समझना", english: "Understand", example: "I understand now.", exampleHindi: "अब समझ गया" },
  { hindi: "याद रखना", english: "Remember", example: "Remember this.", exampleHindi: "इसे याद रखो" },
  { hindi: "भूलना", english: "Forget", example: "Don’t forget.", exampleHindi: "मत भूलो" },
  { hindi: "बोलना", english: "Speak", example: "Speak clearly.", exampleHindi: "साफ बोलो" },
  { hindi: "सुनना", english: "Listen", example: "Listen carefully.", exampleHindi: "ध्यान से सुनो" },
  { hindi: "पढ़ना", english: "Read", example: "Read daily.", exampleHindi: "रोज पढ़ो" },
  { hindi: "लिखना", english: "Write", example: "Write neatly.", exampleHindi: "साफ लिखो" },
  { hindi: "उपयोग करना", english: "Use", example: "Use this word.", exampleHindi: "इस शब्द का उपयोग करो" },
  { hindi: "शुरू करना", english: "Start", example: "Start now.", exampleHindi: "अभी शुरू करो" },
  { hindi: "खत्म करना", english: "Finish", example: "Finish fast.", exampleHindi: "जल्दी खत्म करो" },
  { hindi: "जारी रखना", english: "Continue", example: "Continue learning.", exampleHindi: "सीखना जारी रखो" },
  { hindi: "रोकना", english: "Stop", example: "Stop here.", exampleHindi: "यहाँ रुक जाओ" },
  { hindi: "इंतजार करना", english: "Wait", example: "Wait a moment.", exampleHindi: "थोड़ा इंतजार करो" },
  { hindi: "मदद करना", english: "Help", example: "Help others.", exampleHindi: "दूसरों की मदद करो" },
  { hindi: "समर्थन करना", english: "Support", example: "Support your team.", exampleHindi: "टीम का समर्थन करो" },
  { hindi: "नेतृत्व करना", english: "Lead", example: "Lead the group.", exampleHindi: "समूह का नेतृत्व करो" },
  { hindi: "अनुसरण करना", english: "Follow", example: "Follow rules.", exampleHindi: "नियमों का पालन करो" },
  { hindi: "जीतना", english: "Win", example: "Win the game.", exampleHindi: "खेल जीतो" },
  { hindi: "हारना", english: "Lose", example: "Don’t lose hope.", exampleHindi: "उम्मीद मत हारो" },
  { hindi: "कोशिश करना", english: "Try", example: "Try your best.", exampleHindi: "पूरी कोशिश करो" },
  { hindi: "सुधारना", english: "Improve", example: "Improve fast.", exampleHindi: "जल्दी सुधार करो" },
  { hindi: "बढ़ना", english: "Grow", example: "Grow daily.", exampleHindi: "रोज बढ़ो" },
  { hindi: "बदलना", english: "Change", example: "Change yourself.", exampleHindi: "खुद को बदलो" },
  { hindi: "सीखना", english: "Learn", example: "Learn English.", exampleHindi: "अंग्रेजी सीखो" },
  { hindi: "अभ्यास करना", english: "Practice", example: "Practice more.", exampleHindi: "ज्यादा अभ्यास करो" },
  { hindi: "दोहराना", english: "Repeat", example: "Repeat again.", exampleHindi: "फिर दोहराओ" },
  { hindi: "ध्यान देना", english: "Focus", example: "Stay focused.", exampleHindi: "ध्यान बनाए रखो" },
  { hindi: "हासिल करना", english: "Achieve", example: "Achieve success.", exampleHindi: "सफलता हासिल करो" },
  { hindi: "समझदार", english: "Smart", example: "Be smart.", exampleHindi: "समझदार बनो" },
  { hindi: "मजबूत", english: "Strong", example: "Stay strong.", exampleHindi: "मजबूत रहो" },
  { hindi: "कमजोर", english: "Weak", example: "Don’t be weak.", exampleHindi: "कमजोर मत बनो" },
  { hindi: "सक्रिय", english: "Active", example: "Stay active.", exampleHindi: "सक्रिय रहो" },
  { hindi: "आलसी", english: "Lazy", example: "Don’t be lazy.", exampleHindi: "आलसी मत बनो" },
  { hindi: "तेज", english: "Quick", example: "Be quick.", exampleHindi: "तेज बनो" },
  { hindi: "धीमा", english: "Slow", example: "Don’t be slow.", exampleHindi: "धीमे मत बनो" },
  { hindi: "साफ", english: "Clear", example: "Keep it clear.", exampleHindi: "साफ रखो" },
  { hindi: "सरल", english: "Simple", example: "Keep it simple.", exampleHindi: "सरल रखो" },
  { hindi: "कठिन", english: "Difficult", example: "This is difficult.", exampleHindi: "यह कठिन है" },
  { hindi: "महत्वपूर्ण", english: "Important", example: "This is important.", exampleHindi: "यह महत्वपूर्ण है" },
  { hindi: "उपयोगी", english: "Useful", example: "This is useful.", exampleHindi: "यह उपयोगी है" },
  { hindi: "सहायक", english: "Helpful", example: "This is helpful.", exampleHindi: "यह सहायक है" },
  { hindi: "आसान", english: "Easy", example: "This is easy.", exampleHindi: "यह आसान है" },
  { hindi: "कठिन", english: "Hard", example: "Work hard.", exampleHindi: "मेहनत करो" },
  { hindi: "सही", english: "Right", example: "This is right.", exampleHindi: "यह सही है" },
  { hindi: "गलत", english: "Wrong", example: "This is wrong.", exampleHindi: "यह गलत है" },
  { hindi: "सबसे अच्छा", english: "Best", example: "Do your best.", exampleHindi: "अपना सर्वश्रेष्ठ करो" },
  { hindi: "बेहतर", english: "Better", example: "Do better.", exampleHindi: "बेहतर करो" },
  { hindi: "अच्छा", english: "Good", example: "Good job.", exampleHindi: "अच्छा काम" },
  { hindi: "बुरा", english: "Bad", example: "Bad habit.", exampleHindi: "बुरी आदत" },
  { hindi: "नया", english: "New", example: "Learn new words.", exampleHindi: "नए शब्द सीखो" },
  { hindi: "पुराना", english: "Old", example: "This is old.", exampleHindi: "यह पुराना है" },
  { hindi: "ऊंचा", english: "High", example: "High goal.", exampleHindi: "ऊंचा लक्ष्य" },
  { hindi: "नीचा", english: "Low", example: "Low score.", exampleHindi: "कम अंक" },
  { hindi: "जल्दी", english: "Early", example: "Wake early.", exampleHindi: "जल्दी उठो" },
  { hindi: "देर", english: "Late", example: "Don’t be late.", exampleHindi: "देर मत करो" },
  { hindi: "आज", english: "Today", example: "Study today.", exampleHindi: "आज पढ़ो" },
  { hindi: "कल", english: "Tomorrow", example: "Do tomorrow.", exampleHindi: "कल करो" },
  { hindi: "रणनीति", english: "Strategy", example: "Make a strategy.", exampleHindi: "एक रणनीति बनाओ" },
  { hindi: "प्रदर्शन", english: "Performance", example: "Improve performance.", exampleHindi: "प्रदर्शन सुधारो" },
  { hindi: "कुशल", english: "Efficient", example: "Be efficient.", exampleHindi: "कुशल बनो" },
  { hindi: "प्रभावी", english: "Effective", example: "Be effective.", exampleHindi: "प्रभावी बनो" },
  { hindi: "उत्पादकता", english: "Productivity", example: "Increase productivity.", exampleHindi: "उत्पादकता बढ़ाओ" },
  { hindi: "गुणवत्ता", english: "Quality", example: "Maintain quality.", exampleHindi: "गुणवत्ता बनाए रखो" },
  { hindi: "मात्रा", english: "Quantity", example: "Increase quantity.", exampleHindi: "मात्रा बढ़ाओ" },
  { hindi: "मानक", english: "Standard", example: "Follow standards.", exampleHindi: "मानकों का पालन करो" },
  { hindi: "प्रक्रिया", english: "Process", example: "Follow process.", exampleHindi: "प्रक्रिया का पालन करो" },
  { hindi: "प्रणाली", english: "System", example: "Improve system.", exampleHindi: "प्रणाली सुधारो" },
  { hindi: "संरचना", english: "Structure", example: "Build structure.", exampleHindi: "संरचना बनाओ" },
  { hindi: "ढांचा", english: "Framework", example: "Use framework.", exampleHindi: "ढांचा उपयोग करो" },
  { hindi: "मॉडल", english: "Model", example: "Create a model.", exampleHindi: "मॉडल बनाओ" },
  { hindi: "तरीका", english: "Method", example: "Use this method.", exampleHindi: "इस तरीके का उपयोग करो" },
  { hindi: "तकनीक", english: "Technique", example: "Learn technique.", exampleHindi: "तकनीक सीखो" },
  { hindi: "दृष्टिकोण", english: "Approach", example: "Change approach.", exampleHindi: "दृष्टिकोण बदलो" },
  { hindi: "अवधारणा", english: "Concept", example: "Understand concept.", exampleHindi: "अवधारणा समझो" },
  { hindi: "सिद्धांत", english: "Theory", example: "Study theory.", exampleHindi: "सिद्धांत पढ़ो" },
  { hindi: "सिद्धांत", english: "Principle", example: "Follow principles.", exampleHindi: "सिद्धांतों का पालन करो" },
  { hindi: "तर्क", english: "Logic", example: "Use logic.", exampleHindi: "तर्क का उपयोग करो" },
  { hindi: "विश्लेषण करना", english: "Analyze", example: "Analyze deeply.", exampleHindi: "गहराई से विश्लेषण करो" },
  { hindi: "मूल्यांकन करना", english: "Evaluate", example: "Evaluate performance.", exampleHindi: "प्रदर्शन का मूल्यांकन करो" },
  { hindi: "आकलन करना", english: "Assess", example: "Assess situation.", exampleHindi: "स्थिति का आकलन करो" },
  { hindi: "जांच करना", english: "Examine", example: "Examine carefully.", exampleHindi: "ध्यान से जांचो" },
  { hindi: "समीक्षा करना", english: "Review", example: "Review work.", exampleHindi: "काम की समीक्षा करो" },
  { hindi: "निरीक्षण करना", english: "Inspect", example: "Inspect quality.", exampleHindi: "गुणवत्ता जांचो" },
  { hindi: "निगरानी करना", english: "Monitor", example: "Monitor progress.", exampleHindi: "प्रगति पर नजर रखो" },
  { hindi: "मापना", english: "Measure", example: "Measure results.", exampleHindi: "परिणाम मापो" },
  { hindi: "तुलना करना", english: "Compare", example: "Compare options.", exampleHindi: "विकल्पों की तुलना करो" },
  { hindi: "अंतर बताना", english: "Contrast", example: "Contrast clearly.", exampleHindi: "अंतर स्पष्ट करो" },
  { hindi: "लागू करना", english: "Implement", example: "Implement plan.", exampleHindi: "योजना लागू करो" },
  { hindi: "क्रियान्वित करना", english: "Execute", example: "Execute strategy.", exampleHindi: "रणनीति लागू करो" },
  { hindi: "संचालित करना", english: "Operate", example: "Operate system.", exampleHindi: "सिस्टम चलाओ" },
  { hindi: "प्रबंधित करना", english: "Manage", example: "Manage tasks.", exampleHindi: "कार्य संभालो" },
  { hindi: "संभालना", english: "Handle", example: "Handle pressure.", exampleHindi: "दबाव संभालो" },
  { hindi: "नियंत्रण करना", english: "Control", example: "Control system.", exampleHindi: "सिस्टम नियंत्रित करो" },
  { hindi: "नियंत्रित करना", english: "Regulate", example: "Regulate process.", exampleHindi: "प्रक्रिया नियंत्रित करो" },
  { hindi: "बनाए रखना", english: "Maintain", example: "Maintain balance.", exampleHindi: "संतुलन बनाए रखो" },
  { hindi: "बनाए रखना", english: "Sustain", example: "Sustain growth.", exampleHindi: "विकास बनाए रखो" },
  { hindi: "समर्थन करना", english: "Support", example: "Support team.", exampleHindi: "टीम का समर्थन करो" },
  { hindi: "विकसित करना", english: "Develop", example: "Develop system.", exampleHindi: "सिस्टम विकसित करो" },
  { hindi: "बढ़ाना", english: "Enhance", example: "Enhance quality.", exampleHindi: "गुणवत्ता बढ़ाओ" },
  { hindi: "सुधारना", english: "Improve", example: "Improve skills.", exampleHindi: "skills सुधारो" },
  { hindi: "उन्नत करना", english: "Upgrade", example: "Upgrade system.", exampleHindi: "सिस्टम अपग्रेड करो" },
  { hindi: "अनुकूल बनाना", english: "Optimize", example: "Optimize process.", exampleHindi: "प्रक्रिया बेहतर बनाओ" },
  { hindi: "नवाचार करना", english: "Innovate", example: "Innovate ideas.", exampleHindi: "नए विचार लाओ" },
  { hindi: "बदलना", english: "Transform", example: "Transform system.", exampleHindi: "सिस्टम बदलो" },
  { hindi: "विस्तार करना", english: "Expand", example: "Expand business.", exampleHindi: "व्यवसाय बढ़ाओ" },
  { hindi: "बढ़ना", english: "Grow", example: "Grow rapidly.", exampleHindi: "तेजी से बढ़ो" },
  { hindi: "आगे बढ़ना", english: "Advance", example: "Advance skills.", exampleHindi: "skills आगे बढ़ाओ" },
  { hindi: "निर्णय", english: "Decision", example: "Make decision.", exampleHindi: "निर्णय लो" },
  { hindi: "निर्णय क्षमता", english: "Judgment", example: "Use judgment.", exampleHindi: "निर्णय क्षमता का उपयोग करो" },
  { hindi: "चयन", english: "Choice", example: "Make choice.", exampleHindi: "चयन करो" },
  { hindi: "विकल्प", english: "Option", example: "Choose option.", exampleHindi: "विकल्प चुनो" },
  { hindi: "विकल्प", english: "Alternative", example: "Find alternative.", exampleHindi: "विकल्प ढूंढो" },
  { hindi: "समाधान", english: "Solution", example: "Find solution.", exampleHindi: "समाधान ढूंढो" },
  { hindi: "समस्या", english: "Problem", example: "Solve problem.", exampleHindi: "समस्या हल करो" },
  { hindi: "चुनौती", english: "Challenge", example: "Face challenge.", exampleHindi: "चुनौती का सामना करो" },
  { hindi: "जोखिम", english: "Risk", example: "Take risk.", exampleHindi: "जोखिम लो" },
  { hindi: "अवसर", english: "Opportunity", example: "Grab opportunity.", exampleHindi: "अवसर पकड़ो" },
  { hindi: "संचार", english: "Communication", example: "Improve communication.", exampleHindi: "संचार सुधारो" },
  { hindi: "परस्पर क्रिया", english: "Interaction", example: "Increase interaction.", exampleHindi: "बातचीत बढ़ाओ" },
  { hindi: "सहयोग", english: "Collaboration", example: "Work in collaboration.", exampleHindi: "सहयोग से काम करो" },
  { hindi: "समन्वय", english: "Coordination", example: "Maintain coordination.", exampleHindi: "समन्वय बनाए रखो" },
  { hindi: "चर्चा", english: "Discussion", example: "Start discussion.", exampleHindi: "चर्चा शुरू करो" },
  { hindi: "प्रस्तुति", english: "Presentation", example: "Give presentation.", exampleHindi: "प्रस्तुति दो" },
  { hindi: "व्याख्या", english: "Explanation", example: "Give explanation.", exampleHindi: "व्याख्या दो" },
  { hindi: "अभिव्यक्ति", english: "Expression", example: "Express clearly.", exampleHindi: "स्पष्ट व्यक्त करो" },
  { hindi: "प्रतिक्रिया", english: "Feedback", example: "Give feedback.", exampleHindi: "प्रतिक्रिया दो" },
  { hindi: "प्रतिक्रिया", english: "Response", example: "Give response.", exampleHindi: "जवाब दो" },
  { hindi: "नेतृत्व", english: "Leadership", example: "Show leadership.", exampleHindi: "नेतृत्व दिखाओ" },
  { hindi: "प्रबंधन", english: "Management", example: "Learn management.", exampleHindi: "प्रबंधन सीखो" },
  { hindi: "संगठन", english: "Organization", example: "Build organization.", exampleHindi: "संगठन बनाओ" },
  { hindi: "जिम्मेदारी", english: "Responsibility", example: "Take responsibility.", exampleHindi: "जिम्मेदारी लो" },
  { hindi: "जवाबदेही", english: "Accountability", example: "Maintain accountability.", exampleHindi: "जवाबदेही निभाओ" },
  { hindi: "अधिकार", english: "Authority", example: "Use authority.", exampleHindi: "अधिकार का उपयोग करो" },
  { hindi: "अनुशासन", english: "Discipline", example: "Follow discipline.", exampleHindi: "अनुशासन का पालन करो" },
  { hindi: "प्रतिबद्धता", english: "Commitment", example: "Show commitment.", exampleHindi: "प्रतिबद्धता दिखाओ" },
  { hindi: "समर्पण", english: "Dedication", example: "Work with dedication.", exampleHindi: "समर्पण से काम करो" },
  { hindi: "निरंतरता", english: "Consistency", example: "Maintain consistency.", exampleHindi: "निरंतरता बनाए रखो" },
  { hindi: "ज्ञान", english: "Knowledge", example: "Gain knowledge.", exampleHindi: "ज्ञान प्राप्त करो" },
  { hindi: "जानकारी", english: "Information", example: "Collect information.", exampleHindi: "जानकारी इकट्ठा करो" },
  { hindi: "डेटा", english: "Data", example: "Analyze data.", exampleHindi: "डेटा का विश्लेषण करो" },
  { hindi: "अनुसंधान", english: "Research", example: "Do research.", exampleHindi: "अनुसंधान करो" },
  { hindi: "अध्ययन", english: "Study", example: "Study deeply.", exampleHindi: "गहराई से पढ़ो" },
  { hindi: "सीखना", english: "Learning", example: "Continuous learning.", exampleHindi: "लगातार सीखो" },
  { hindi: "शिक्षा", english: "Education", example: "Value education.", exampleHindi: "शिक्षा को महत्व दो" },
  { hindi: "कौशल", english: "Skill", example: "Build skill.", exampleHindi: "कौशल बनाओ" },
  { hindi: "क्षमता", english: "Ability", example: "Improve ability.", exampleHindi: "क्षमता बढ़ाओ" },
  { hindi: "योग्यता", english: "Capability", example: "Show capability.", exampleHindi: "योग्यता दिखाओ" },
  { hindi: "मजबूत", english: "Strong", example: "Stay strong.", exampleHindi: "मजबूत रहो" },
  { hindi: "कमजोर", english: "Weak", example: "Avoid weakness.", exampleHindi: "कमजोरी दूर करो" },
  { hindi: "शक्तिशाली", english: "Powerful", example: "Be powerful.", exampleHindi: "शक्तिशाली बनो" },
  { hindi: "स्थिर", english: "Stable", example: "Stay stable.", exampleHindi: "स्थिर रहो" },
  { hindi: "लचीला", english: "Flexible", example: "Be flexible.", exampleHindi: "लचीले बनो" },
  { hindi: "गतिशील", english: "Dynamic", example: "Be dynamic.", exampleHindi: "गतिशील बनो" },
  { hindi: "सक्रिय", english: "Active", example: "Stay active.", exampleHindi: "सक्रिय रहो" },
  { hindi: "निष्क्रिय", english: "Passive", example: "Avoid passive.", exampleHindi: "निष्क्रिय मत बनो" },
  { hindi: "सकारात्मक", english: "Positive", example: "Stay positive.", exampleHindi: "सकारात्मक रहो" },
  { hindi: "नकारात्मक", english: "Negative", example: "Avoid negative.", exampleHindi: "नकारात्मकता दूर करो" },
  { hindi: "जटिल", english: "Complex", example: "This is complex.", exampleHindi: "यह जटिल है" },
  { hindi: "सरल", english: "Simple", example: "Keep it simple.", exampleHindi: "सरल रखो" },
  { hindi: "स्पष्ट", english: "Clear", example: "Be clear.", exampleHindi: "स्पष्ट रहो" },
  { hindi: "सटीक", english: "Accurate", example: "Be accurate.", exampleHindi: "सटीक बनो" },
  { hindi: "सटीक", english: "Precise", example: "Give precise answer.", exampleHindi: "सटीक उत्तर दो" },
  { hindi: "बिल्कुल सही", english: "Exact", example: "Exact result.", exampleHindi: "बिल्कुल सही परिणाम" },
  { hindi: "अनुमानित", english: "Approximate", example: "Approximate value.", exampleHindi: "अनुमानित मान" },
  { hindi: "संबंधित", english: "Relevant", example: "Relevant data.", exampleHindi: "संबंधित डेटा" },
  { hindi: "महत्वपूर्ण", english: "Important", example: "Important topic.", exampleHindi: "महत्वपूर्ण विषय" },
  { hindi: "आवश्यक", english: "Essential", example: "Essential skill.", exampleHindi: "आवश्यक कौशल" },
  { hindi: "शुरू करना", english: "Begin", example: "Begin process.", exampleHindi: "प्रक्रिया शुरू करो" },
  { hindi: "जारी रखना", english: "Continue", example: "Continue work.", exampleHindi: "काम जारी रखो" },
  { hindi: "रोकना", english: "Pause", example: "Pause now.", exampleHindi: "अभी रोक दो" },
  { hindi: "फिर शुरू करना", english: "Resume", example: "Resume task.", exampleHindi: "कार्य फिर शुरू करो" },
  { hindi: "रोकना", english: "Stop", example: "Stop errors.", exampleHindi: "गलतियाँ रोको" },
  { hindi: "खत्म करना", english: "Finish", example: "Finish task.", exampleHindi: "कार्य खत्म करो" },
  { hindi: "पूरा करना", english: "Complete", example: "Complete properly.", exampleHindi: "सही पूरा करो" },
  { hindi: "प्राप्त करना", english: "Achieve", example: "Achieve target.", exampleHindi: "लक्ष्य प्राप्त करो" },
  { hindi: "सफल होना", english: "Succeed", example: "Succeed always.", exampleHindi: "हमेशा सफल हो" },
  { hindi: "पूरा करना", english: "Accomplish", example: "Accomplish goals.", exampleHindi: "लक्ष्य पूरे करो" },
];
